/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorSpec from '../model/ErrorSpec';
import NetworkResourceCreateRequest from '../model/NetworkResourceCreateRequest';
import NetworkResourceSpec from '../model/NetworkResourceSpec';

/**
* Network service.
* @module api/NetworkApi
* @version 0.0.3
*/
export default class NetworkApi {

    /**
    * Constructs a new NetworkApi. 
    * @alias module:api/NetworkApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the networkResourceCreate operation.
     * @callback module:api/NetworkApi~networkResourceCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/NetworkResourceSpec} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * create a new network resource.
     * @param {module:model/NetworkResourceCreateRequest} networkResourceCreateRequest parameters for the requested network resource.
     * @param {module:api/NetworkApi~networkResourceCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/NetworkResourceSpec}
     */
    networkResourceCreate(networkResourceCreateRequest, callback) {
      let postBody = networkResourceCreateRequest;
      // verify the required parameter 'networkResourceCreateRequest' is set
      if (networkResourceCreateRequest === undefined || networkResourceCreateRequest === null) {
        throw new Error("Missing the required parameter 'networkResourceCreateRequest' when calling networkResourceCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = NetworkResourceSpec;
      return this.apiClient.callApi(
        '/v1alpha/network_resources', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the networkResourceDelete operation.
     * @callback module:api/NetworkApi~networkResourceDeleteCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * remove specified network resource.
     * @param {String} nrId uuid of network resource created
     * @param {module:model/String} cloudProvider cloud provider name
     * @param {module:api/NetworkApi~networkResourceDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    networkResourceDelete(nrId, cloudProvider, callback) {
      let postBody = null;
      // verify the required parameter 'nrId' is set
      if (nrId === undefined || nrId === null) {
        throw new Error("Missing the required parameter 'nrId' when calling networkResourceDelete");
      }
      // verify the required parameter 'cloudProvider' is set
      if (cloudProvider === undefined || cloudProvider === null) {
        throw new Error("Missing the required parameter 'cloudProvider' when calling networkResourceDelete");
      }

      let pathParams = {
        'nr_id': nrId
      };
      let queryParams = {
        'cloud_provider': cloudProvider
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1alpha/network_resources/{nr_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the networkResourceGet operation.
     * @callback module:api/NetworkApi~networkResourceGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/NetworkResourceSpec} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get the information of network resource.
     * @param {String} nrId uuid of network resource created
     * @param {module:model/String} cloudProvider cloud provider name
     * @param {module:api/NetworkApi~networkResourceGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/NetworkResourceSpec}
     */
    networkResourceGet(nrId, cloudProvider, callback) {
      let postBody = null;
      // verify the required parameter 'nrId' is set
      if (nrId === undefined || nrId === null) {
        throw new Error("Missing the required parameter 'nrId' when calling networkResourceGet");
      }
      // verify the required parameter 'cloudProvider' is set
      if (cloudProvider === undefined || cloudProvider === null) {
        throw new Error("Missing the required parameter 'cloudProvider' when calling networkResourceGet");
      }

      let pathParams = {
        'nr_id': nrId
      };
      let queryParams = {
        'cloud_provider': cloudProvider
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = NetworkResourceSpec;
      return this.apiClient.callApi(
        '/v1alpha/network_resources/{nr_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
