/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudServerResourceFragment {
    #[serde(rename = "hostId", skip_serializing_if = "Option::is_none")]
    pub host_id: Option<String>,
    #[serde(rename = "key_name", skip_serializing_if = "Option::is_none")]
    pub key_name: Option<String>,
    #[serde(
        rename = "OS-EXT-STS:vm_state",
        skip_serializing_if = "Option::is_none"
    )]
    pub os_ext_st_svm_state: Option<String>,
    #[serde(rename = "addresses", skip_serializing_if = "Option::is_none")]
    pub addresses: Option<serde_json::Value>,
    #[serde(rename = "flavor", skip_serializing_if = "Option::is_none")]
    pub flavor: Option<crate::models::CloudServerResourceFragmentFlavor>,
    #[serde(
        rename = "OS-EXT-AZ:availability_zone",
        skip_serializing_if = "Option::is_none"
    )]
    pub os_ext_a_zavailability_zone: Option<String>,
    #[serde(rename = "accessIPv4", skip_serializing_if = "Option::is_none")]
    pub access_i_pv4: Option<String>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    #[serde(
        rename = "os-extended-volumes:volumes_attached",
        skip_serializing_if = "Option::is_none"
    )]
    pub os_extended_volumesvolumes_attached:
        Option<Vec<crate::models::CloudServerResourceFragmentOsextendedvolumesvolumesAttached>>,
    #[serde(
        rename = "OS-EXT-SRV-ATTR:hostname",
        skip_serializing_if = "Option::is_none"
    )]
    pub os_ext_srv_att_rhostname: Option<String>,
}

impl CloudServerResourceFragment {
    pub fn new() -> CloudServerResourceFragment {
        CloudServerResourceFragment {
            host_id: None,
            key_name: None,
            os_ext_st_svm_state: None,
            addresses: None,
            flavor: None,
            os_ext_a_zavailability_zone: None,
            access_i_pv4: None,
            metadata: None,
            os_extended_volumesvolumes_attached: None,
            os_ext_srv_att_rhostname: None,
        }
    }
}
