/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicipRequestFragmentPublicip {
    #[serde(rename = "type")]
    pub _type: String,
    #[serde(rename = "ip_address", skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
}

impl PublicipRequestFragmentPublicip {
    pub fn new(_type: String) -> PublicipRequestFragmentPublicip {
        PublicipRequestFragmentPublicip {
            _type: _type,
            ip_address: None,
        }
    }
}
