/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import BackupRequestFragment from './model/BackupRequestFragment';
import BackupResourceFragment from './model/BackupResourceFragment';
import BandwidthResource from './model/BandwidthResource';
import BlockVolumeRequestFragment from './model/BlockVolumeRequestFragment';
import BlockVolumeResourceFragment from './model/BlockVolumeResourceFragment';
import BlockVolumeResourceFragmentAttachments from './model/BlockVolumeResourceFragmentAttachments';
import CloudProviderInfo from './model/CloudProviderInfo';
import CloudServerRequestFragment from './model/CloudServerRequestFragment';
import CloudServerRequestFragmentNics from './model/CloudServerRequestFragmentNics';
import CloudServerRequestFragmentPublicip from './model/CloudServerRequestFragmentPublicip';
import CloudServerRequestFragmentPublicipEip from './model/CloudServerRequestFragmentPublicipEip';
import CloudServerRequestFragmentRootVolume from './model/CloudServerRequestFragmentRootVolume';
import CloudServerRequestFragmentSecurityGroups from './model/CloudServerRequestFragmentSecurityGroups';
import CloudServerResourceFragment from './model/CloudServerResourceFragment';
import CloudServerResourceFragmentFlavor from './model/CloudServerResourceFragmentFlavor';
import CloudServerResourceFragmentOsextendedvolumesvolumesAttached from './model/CloudServerResourceFragmentOsextendedvolumesvolumesAttached';
import ComputeResourceCreateRequest from './model/ComputeResourceCreateRequest';
import ComputeResourceSpec from './model/ComputeResourceSpec';
import ErrorSpec from './model/ErrorSpec';
import FileShareRequestFragment from './model/FileShareRequestFragment';
import FileShareResourceFragment from './model/FileShareResourceFragment';
import FileShareResourceFragmentExportLocations from './model/FileShareResourceFragmentExportLocations';
import NetworkResourceCreateRequest from './model/NetworkResourceCreateRequest';
import NetworkResourceSpec from './model/NetworkResourceSpec';
import PublicipRequestFragment from './model/PublicipRequestFragment';
import PublicipRequestFragmentPublicip from './model/PublicipRequestFragmentPublicip';
import PublicipResourceFragment from './model/PublicipResourceFragment';
import StorageResourceCreateRequest from './model/StorageResourceCreateRequest';
import StorageResourceSpec from './model/StorageResourceSpec';
import SubnetRequestFragment from './model/SubnetRequestFragment';
import SubnetResourceFragment from './model/SubnetResourceFragment';
import VPCRequestFragment from './model/VPCRequestFragment';
import VPCResourceFragment from './model/VPCResourceFragment';
import VPCResourceFragmentRoutes from './model/VPCResourceFragmentRoutes';
import ComputeApi from './api/ComputeApi';
import NetworkApi from './api/NetworkApi';
import StorageApi from './api/StorageApi';


/**
* Open_Service_Cloud_API_to_manage_different_backend_cloud_services_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenServiceCloudApi = require('index'); // See note below*.
* var xxxSvc = new OpenServiceCloudApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OpenServiceCloudApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenServiceCloudApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OpenServiceCloudApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.3
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The BackupRequestFragment model constructor.
     * @property {module:model/BackupRequestFragment}
     */
    BackupRequestFragment,

    /**
     * The BackupResourceFragment model constructor.
     * @property {module:model/BackupResourceFragment}
     */
    BackupResourceFragment,

    /**
     * The BandwidthResource model constructor.
     * @property {module:model/BandwidthResource}
     */
    BandwidthResource,

    /**
     * The BlockVolumeRequestFragment model constructor.
     * @property {module:model/BlockVolumeRequestFragment}
     */
    BlockVolumeRequestFragment,

    /**
     * The BlockVolumeResourceFragment model constructor.
     * @property {module:model/BlockVolumeResourceFragment}
     */
    BlockVolumeResourceFragment,

    /**
     * The BlockVolumeResourceFragmentAttachments model constructor.
     * @property {module:model/BlockVolumeResourceFragmentAttachments}
     */
    BlockVolumeResourceFragmentAttachments,

    /**
     * The CloudProviderInfo model constructor.
     * @property {module:model/CloudProviderInfo}
     */
    CloudProviderInfo,

    /**
     * The CloudServerRequestFragment model constructor.
     * @property {module:model/CloudServerRequestFragment}
     */
    CloudServerRequestFragment,

    /**
     * The CloudServerRequestFragmentNics model constructor.
     * @property {module:model/CloudServerRequestFragmentNics}
     */
    CloudServerRequestFragmentNics,

    /**
     * The CloudServerRequestFragmentPublicip model constructor.
     * @property {module:model/CloudServerRequestFragmentPublicip}
     */
    CloudServerRequestFragmentPublicip,

    /**
     * The CloudServerRequestFragmentPublicipEip model constructor.
     * @property {module:model/CloudServerRequestFragmentPublicipEip}
     */
    CloudServerRequestFragmentPublicipEip,

    /**
     * The CloudServerRequestFragmentRootVolume model constructor.
     * @property {module:model/CloudServerRequestFragmentRootVolume}
     */
    CloudServerRequestFragmentRootVolume,

    /**
     * The CloudServerRequestFragmentSecurityGroups model constructor.
     * @property {module:model/CloudServerRequestFragmentSecurityGroups}
     */
    CloudServerRequestFragmentSecurityGroups,

    /**
     * The CloudServerResourceFragment model constructor.
     * @property {module:model/CloudServerResourceFragment}
     */
    CloudServerResourceFragment,

    /**
     * The CloudServerResourceFragmentFlavor model constructor.
     * @property {module:model/CloudServerResourceFragmentFlavor}
     */
    CloudServerResourceFragmentFlavor,

    /**
     * The CloudServerResourceFragmentOsextendedvolumesvolumesAttached model constructor.
     * @property {module:model/CloudServerResourceFragmentOsextendedvolumesvolumesAttached}
     */
    CloudServerResourceFragmentOsextendedvolumesvolumesAttached,

    /**
     * The ComputeResourceCreateRequest model constructor.
     * @property {module:model/ComputeResourceCreateRequest}
     */
    ComputeResourceCreateRequest,

    /**
     * The ComputeResourceSpec model constructor.
     * @property {module:model/ComputeResourceSpec}
     */
    ComputeResourceSpec,

    /**
     * The ErrorSpec model constructor.
     * @property {module:model/ErrorSpec}
     */
    ErrorSpec,

    /**
     * The FileShareRequestFragment model constructor.
     * @property {module:model/FileShareRequestFragment}
     */
    FileShareRequestFragment,

    /**
     * The FileShareResourceFragment model constructor.
     * @property {module:model/FileShareResourceFragment}
     */
    FileShareResourceFragment,

    /**
     * The FileShareResourceFragmentExportLocations model constructor.
     * @property {module:model/FileShareResourceFragmentExportLocations}
     */
    FileShareResourceFragmentExportLocations,

    /**
     * The NetworkResourceCreateRequest model constructor.
     * @property {module:model/NetworkResourceCreateRequest}
     */
    NetworkResourceCreateRequest,

    /**
     * The NetworkResourceSpec model constructor.
     * @property {module:model/NetworkResourceSpec}
     */
    NetworkResourceSpec,

    /**
     * The PublicipRequestFragment model constructor.
     * @property {module:model/PublicipRequestFragment}
     */
    PublicipRequestFragment,

    /**
     * The PublicipRequestFragmentPublicip model constructor.
     * @property {module:model/PublicipRequestFragmentPublicip}
     */
    PublicipRequestFragmentPublicip,

    /**
     * The PublicipResourceFragment model constructor.
     * @property {module:model/PublicipResourceFragment}
     */
    PublicipResourceFragment,

    /**
     * The StorageResourceCreateRequest model constructor.
     * @property {module:model/StorageResourceCreateRequest}
     */
    StorageResourceCreateRequest,

    /**
     * The StorageResourceSpec model constructor.
     * @property {module:model/StorageResourceSpec}
     */
    StorageResourceSpec,

    /**
     * The SubnetRequestFragment model constructor.
     * @property {module:model/SubnetRequestFragment}
     */
    SubnetRequestFragment,

    /**
     * The SubnetResourceFragment model constructor.
     * @property {module:model/SubnetResourceFragment}
     */
    SubnetResourceFragment,

    /**
     * The VPCRequestFragment model constructor.
     * @property {module:model/VPCRequestFragment}
     */
    VPCRequestFragment,

    /**
     * The VPCResourceFragment model constructor.
     * @property {module:model/VPCResourceFragment}
     */
    VPCResourceFragment,

    /**
     * The VPCResourceFragmentRoutes model constructor.
     * @property {module:model/VPCResourceFragmentRoutes}
     */
    VPCResourceFragmentRoutes,

    /**
    * The ComputeApi service constructor.
    * @property {module:api/ComputeApi}
    */
    ComputeApi,

    /**
    * The NetworkApi service constructor.
    * @property {module:api/NetworkApi}
    */
    NetworkApi,

    /**
    * The StorageApi service constructor.
    * @property {module:api/StorageApi}
    */
    StorageApi
};
