/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct BackupResourceFragment {
    #[serde(rename = "volume_id", skip_serializing_if = "Option::is_none")]
    pub volume_id: Option<String>,
    #[serde(rename = "container", skip_serializing_if = "Option::is_none")]
    pub container: Option<String>,
    #[serde(rename = "service_metadata", skip_serializing_if = "Option::is_none")]
    pub service_metadata: Option<String>,
    #[serde(rename = "snapshot_id", skip_serializing_if = "Option::is_none")]
    pub snapshot_id: Option<String>,
    #[serde(rename = "is_incremental", skip_serializing_if = "Option::is_none")]
    pub is_incremental: Option<bool>,
}

impl BackupResourceFragment {
    pub fn new() -> BackupResourceFragment {
        BackupResourceFragment {
            volume_id: None,
            container: None,
            service_metadata: None,
            snapshot_id: None,
            is_incremental: None,
        }
    }
}
