/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudServerRequestFragmentRootVolume {
    #[serde(rename = "volumetype")]
    pub volumetype: String,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
}

impl CloudServerRequestFragmentRootVolume {
    pub fn new(volumetype: String) -> CloudServerRequestFragmentRootVolume {
        CloudServerRequestFragmentRootVolume {
            volumetype: volumetype,
            size: None,
        }
    }
}
