/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: https://openapi-generator.tech
 */

/// ComputeResourceSpec : Detailed info that indicates the type of backend cloud storage services.

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct ComputeResourceSpec {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
    #[serde(rename = "cloud_provider", skip_serializing_if = "Option::is_none")]
    pub cloud_provider: Option<crate::models::CloudProviderInfo>,
    #[serde(
        rename = "cloud_server_fragment",
        skip_serializing_if = "Option::is_none"
    )]
    pub cloud_server_fragment: Option<crate::models::CloudServerResourceFragment>,
    #[serde(
        rename = "physical_server_fragment",
        skip_serializing_if = "Option::is_none"
    )]
    pub physical_server_fragment: Option<crate::models::CloudServerResourceFragment>,
    #[serde(rename = "pod_fragment", skip_serializing_if = "Option::is_none")]
    pub pod_fragment: Option<serde_json::Value>,
}

impl ComputeResourceSpec {
    /// Detailed info that indicates the type of backend cloud storage services.
    pub fn new() -> ComputeResourceSpec {
        ComputeResourceSpec {
            id: None,
            name: None,
            description: None,
            status: None,
            created: None,
            updated: None,
            cloud_provider: None,
            cloud_server_fragment: None,
            physical_server_fragment: None,
            pod_fragment: None,
        }
    }
}
