/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct FileShareRequestFragment {
    #[serde(rename = "share_proto")]
    pub share_proto: String,
    #[serde(rename = "share_type", skip_serializing_if = "Option::is_none")]
    pub share_type: Option<String>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    #[serde(rename = "share_network_id", skip_serializing_if = "Option::is_none")]
    pub share_network_id: Option<String>,
}

impl FileShareRequestFragment {
    pub fn new(share_proto: String) -> FileShareRequestFragment {
        FileShareRequestFragment {
            share_proto: share_proto,
            share_type: None,
            metadata: None,
            share_network_id: None,
        }
    }
}
