/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * API version: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		"GET",
		"/",
		Index,
	},

	{
		"ComputeResourceCreate",
		strings.ToUpper("Post"),
		"/v1alpha/compute_resources",
		ComputeResourceCreate,
	},

	{
		"ComputeResourceDelete",
		strings.ToUpper("Delete"),
		"/v1alpha/compute_resources/{cr_id}",
		ComputeResourceDelete,
	},

	{
		"ComputeResourceGet",
		strings.ToUpper("Get"),
		"/v1alpha/compute_resources/{cr_id}",
		ComputeResourceGet,
	},

	{
		"NetworkResourceCreate",
		strings.ToUpper("Post"),
		"/v1alpha/network_resources",
		NetworkResourceCreate,
	},

	{
		"NetworkResourceDelete",
		strings.ToUpper("Delete"),
		"/v1alpha/network_resources/{nr_id}",
		NetworkResourceDelete,
	},

	{
		"NetworkResourceGet",
		strings.ToUpper("Get"),
		"/v1alpha/network_resources/{nr_id}",
		NetworkResourceGet,
	},

	{
		"StorageResourceCreate",
		strings.ToUpper("Post"),
		"/v1alpha/storage_resources",
		StorageResourceCreate,
	},

	{
		"StorageResourceDelete",
		strings.ToUpper("Delete"),
		"/v1alpha/storage_resources/{sr_id}",
		StorageResourceDelete,
	},

	{
		"StorageResourceGet",
		strings.ToUpper("Get"),
		"/v1alpha/storage_resources/{sr_id}",
		StorageResourceGet,
	},
}
