/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BackupResourceFragment model module.
 * @module model/BackupResourceFragment
 * @version 0.0.3
 */
class BackupResourceFragment {
    /**
     * Constructs a new <code>BackupResourceFragment</code>.
     * @alias module:model/BackupResourceFragment
     */
    constructor() { 
        
        BackupResourceFragment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BackupResourceFragment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BackupResourceFragment} obj Optional instance to populate.
     * @return {module:model/BackupResourceFragment} The populated <code>BackupResourceFragment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BackupResourceFragment();

            if (data.hasOwnProperty('volume_id')) {
                obj['volume_id'] = ApiClient.convertToType(data['volume_id'], 'String');
            }
            if (data.hasOwnProperty('container')) {
                obj['container'] = ApiClient.convertToType(data['container'], 'String');
            }
            if (data.hasOwnProperty('service_metadata')) {
                obj['service_metadata'] = ApiClient.convertToType(data['service_metadata'], 'String');
            }
            if (data.hasOwnProperty('snapshot_id')) {
                obj['snapshot_id'] = ApiClient.convertToType(data['snapshot_id'], 'String');
            }
            if (data.hasOwnProperty('is_incremental')) {
                obj['is_incremental'] = ApiClient.convertToType(data['is_incremental'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} volume_id
 */
BackupResourceFragment.prototype['volume_id'] = undefined;

/**
 * @member {String} container
 */
BackupResourceFragment.prototype['container'] = undefined;

/**
 * @member {String} service_metadata
 */
BackupResourceFragment.prototype['service_metadata'] = undefined;

/**
 * @member {String} snapshot_id
 */
BackupResourceFragment.prototype['snapshot_id'] = undefined;

/**
 * @member {Boolean} is_incremental
 */
BackupResourceFragment.prototype['is_incremental'] = undefined;






export default BackupResourceFragment;

