/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BackupRequestFragment model module.
 * @module model/BackupRequestFragment
 * @version 0.0.3
 */
class BackupRequestFragment {
    /**
     * Constructs a new <code>BackupRequestFragment</code>.
     * @alias module:model/BackupRequestFragment
     * @param volumeId {String} 
     * @param snapshotId {String} 
     */
    constructor(volumeId, snapshotId) { 
        
        BackupRequestFragment.initialize(this, volumeId, snapshotId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, volumeId, snapshotId) { 
        obj['volume_id'] = volumeId;
        obj['snapshot_id'] = snapshotId;
    }

    /**
     * Constructs a <code>BackupRequestFragment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BackupRequestFragment} obj Optional instance to populate.
     * @return {module:model/BackupRequestFragment} The populated <code>BackupRequestFragment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BackupRequestFragment();

            if (data.hasOwnProperty('volume_id')) {
                obj['volume_id'] = ApiClient.convertToType(data['volume_id'], 'String');
            }
            if (data.hasOwnProperty('snapshot_id')) {
                obj['snapshot_id'] = ApiClient.convertToType(data['snapshot_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} volume_id
 */
BackupRequestFragment.prototype['volume_id'] = undefined;

/**
 * @member {String} snapshot_id
 */
BackupRequestFragment.prototype['snapshot_id'] = undefined;






export default BackupRequestFragment;

