/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BandwidthResource model module.
 * @module model/BandwidthResource
 * @version 0.0.3
 */
class BandwidthResource {
    /**
     * Constructs a new <code>BandwidthResource</code>.
     * @alias module:model/BandwidthResource
     * @param sharetype {module:model/BandwidthResource.SharetypeEnum} 
     */
    constructor(sharetype) { 
        
        BandwidthResource.initialize(this, sharetype);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, sharetype) { 
        obj['sharetype'] = sharetype;
    }

    /**
     * Constructs a <code>BandwidthResource</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BandwidthResource} obj Optional instance to populate.
     * @return {module:model/BandwidthResource} The populated <code>BandwidthResource</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BandwidthResource();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('sharetype')) {
                obj['sharetype'] = ApiClient.convertToType(data['sharetype'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
BandwidthResource.prototype['name'] = undefined;

/**
 * @member {module:model/BandwidthResource.SharetypeEnum} sharetype
 */
BandwidthResource.prototype['sharetype'] = undefined;

/**
 * @member {Number} size
 * @default 1
 */
BandwidthResource.prototype['size'] = 1;





/**
 * Allowed values for the <code>sharetype</code> property.
 * @enum {String}
 * @readonly
 */
BandwidthResource['SharetypeEnum'] = {

    /**
     * value: "PER"
     * @const
     */
    "PER": "PER",

    /**
     * value: "WHOLE"
     * @const
     */
    "WHOLE": "WHOLE"
};



export default BandwidthResource;

