/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BlockVolumeResourceFragmentAttachments model module.
 * @module model/BlockVolumeResourceFragmentAttachments
 * @version 0.0.3
 */
class BlockVolumeResourceFragmentAttachments {
    /**
     * Constructs a new <code>BlockVolumeResourceFragmentAttachments</code>.
     * @alias module:model/BlockVolumeResourceFragmentAttachments
     */
    constructor() { 
        
        BlockVolumeResourceFragmentAttachments.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BlockVolumeResourceFragmentAttachments</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BlockVolumeResourceFragmentAttachments} obj Optional instance to populate.
     * @return {module:model/BlockVolumeResourceFragmentAttachments} The populated <code>BlockVolumeResourceFragmentAttachments</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BlockVolumeResourceFragmentAttachments();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('server_id')) {
                obj['server_id'] = ApiClient.convertToType(data['server_id'], 'String');
            }
            if (data.hasOwnProperty('volume_id')) {
                obj['volume_id'] = ApiClient.convertToType(data['volume_id'], 'String');
            }
            if (data.hasOwnProperty('attachment_id')) {
                obj['attachment_id'] = ApiClient.convertToType(data['attachment_id'], 'String');
            }
            if (data.hasOwnProperty('device')) {
                obj['device'] = ApiClient.convertToType(data['device'], 'String');
            }
            if (data.hasOwnProperty('host_name')) {
                obj['host_name'] = ApiClient.convertToType(data['host_name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
BlockVolumeResourceFragmentAttachments.prototype['id'] = undefined;

/**
 * @member {String} server_id
 */
BlockVolumeResourceFragmentAttachments.prototype['server_id'] = undefined;

/**
 * @member {String} volume_id
 */
BlockVolumeResourceFragmentAttachments.prototype['volume_id'] = undefined;

/**
 * @member {String} attachment_id
 */
BlockVolumeResourceFragmentAttachments.prototype['attachment_id'] = undefined;

/**
 * @member {String} device
 */
BlockVolumeResourceFragmentAttachments.prototype['device'] = undefined;

/**
 * @member {String} host_name
 */
BlockVolumeResourceFragmentAttachments.prototype['host_name'] = undefined;






export default BlockVolumeResourceFragmentAttachments;

