/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BlockVolumeResourceFragmentAttachments from './BlockVolumeResourceFragmentAttachments';

/**
 * The BlockVolumeResourceFragment model module.
 * @module model/BlockVolumeResourceFragment
 * @version 0.0.3
 */
class BlockVolumeResourceFragment {
    /**
     * Constructs a new <code>BlockVolumeResourceFragment</code>.
     * @alias module:model/BlockVolumeResourceFragment
     */
    constructor() { 
        
        BlockVolumeResourceFragment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BlockVolumeResourceFragment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BlockVolumeResourceFragment} obj Optional instance to populate.
     * @return {module:model/BlockVolumeResourceFragment} The populated <code>BlockVolumeResourceFragment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BlockVolumeResourceFragment();

            if (data.hasOwnProperty('volume_type')) {
                obj['volume_type'] = ApiClient.convertToType(data['volume_type'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
            if (data.hasOwnProperty('os-vol-host-attr:host')) {
                obj['os-vol-host-attr:host'] = ApiClient.convertToType(data['os-vol-host-attr:host'], 'String');
            }
            if (data.hasOwnProperty('multiattach')) {
                obj['multiattach'] = ApiClient.convertToType(data['multiattach'], 'Boolean');
            }
            if (data.hasOwnProperty('dedicated_storage_id')) {
                obj['dedicated_storage_id'] = ApiClient.convertToType(data['dedicated_storage_id'], 'String');
            }
            if (data.hasOwnProperty('dedicated_storage_name')) {
                obj['dedicated_storage_name'] = ApiClient.convertToType(data['dedicated_storage_name'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], Object);
            }
            if (data.hasOwnProperty('attachments')) {
                obj['attachments'] = ApiClient.convertToType(data['attachments'], [BlockVolumeResourceFragmentAttachments]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} volume_type
 */
BlockVolumeResourceFragment.prototype['volume_type'] = undefined;

/**
 * @member {Object} metadata
 */
BlockVolumeResourceFragment.prototype['metadata'] = undefined;

/**
 * @member {String} os-vol-host-attr:host
 */
BlockVolumeResourceFragment.prototype['os-vol-host-attr:host'] = undefined;

/**
 * @member {Boolean} multiattach
 */
BlockVolumeResourceFragment.prototype['multiattach'] = undefined;

/**
 * @member {String} dedicated_storage_id
 */
BlockVolumeResourceFragment.prototype['dedicated_storage_id'] = undefined;

/**
 * @member {String} dedicated_storage_name
 */
BlockVolumeResourceFragment.prototype['dedicated_storage_name'] = undefined;

/**
 * @member {Object} tags
 */
BlockVolumeResourceFragment.prototype['tags'] = undefined;

/**
 * @member {Array.<module:model/BlockVolumeResourceFragmentAttachments>} attachments
 */
BlockVolumeResourceFragment.prototype['attachments'] = undefined;






export default BlockVolumeResourceFragment;

