/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CloudServerRequestFragmentSecurityGroups model module.
 * @module model/CloudServerRequestFragmentSecurityGroups
 * @version 0.0.3
 */
class CloudServerRequestFragmentSecurityGroups {
    /**
     * Constructs a new <code>CloudServerRequestFragmentSecurityGroups</code>.
     * @alias module:model/CloudServerRequestFragmentSecurityGroups
     * @param id {String} 
     */
    constructor(id) { 
        
        CloudServerRequestFragmentSecurityGroups.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>CloudServerRequestFragmentSecurityGroups</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CloudServerRequestFragmentSecurityGroups} obj Optional instance to populate.
     * @return {module:model/CloudServerRequestFragmentSecurityGroups} The populated <code>CloudServerRequestFragmentSecurityGroups</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CloudServerRequestFragmentSecurityGroups();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
CloudServerRequestFragmentSecurityGroups.prototype['id'] = undefined;






export default CloudServerRequestFragmentSecurityGroups;

