/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CloudServerResourceFragmentFlavor from './CloudServerResourceFragmentFlavor';
import CloudServerResourceFragmentOsextendedvolumesvolumesAttached from './CloudServerResourceFragmentOsextendedvolumesvolumesAttached';

/**
 * The CloudServerResourceFragment model module.
 * @module model/CloudServerResourceFragment
 * @version 0.0.3
 */
class CloudServerResourceFragment {
    /**
     * Constructs a new <code>CloudServerResourceFragment</code>.
     * @alias module:model/CloudServerResourceFragment
     */
    constructor() { 
        
        CloudServerResourceFragment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CloudServerResourceFragment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CloudServerResourceFragment} obj Optional instance to populate.
     * @return {module:model/CloudServerResourceFragment} The populated <code>CloudServerResourceFragment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CloudServerResourceFragment();

            if (data.hasOwnProperty('hostId')) {
                obj['hostId'] = ApiClient.convertToType(data['hostId'], 'String');
            }
            if (data.hasOwnProperty('key_name')) {
                obj['key_name'] = ApiClient.convertToType(data['key_name'], 'String');
            }
            if (data.hasOwnProperty('OS-EXT-STS:vm_state')) {
                obj['OS-EXT-STS:vm_state'] = ApiClient.convertToType(data['OS-EXT-STS:vm_state'], 'String');
            }
            if (data.hasOwnProperty('addresses')) {
                obj['addresses'] = ApiClient.convertToType(data['addresses'], Object);
            }
            if (data.hasOwnProperty('flavor')) {
                obj['flavor'] = CloudServerResourceFragmentFlavor.constructFromObject(data['flavor']);
            }
            if (data.hasOwnProperty('OS-EXT-AZ:availability_zone')) {
                obj['OS-EXT-AZ:availability_zone'] = ApiClient.convertToType(data['OS-EXT-AZ:availability_zone'], 'String');
            }
            if (data.hasOwnProperty('accessIPv4')) {
                obj['accessIPv4'] = ApiClient.convertToType(data['accessIPv4'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
            if (data.hasOwnProperty('os-extended-volumes:volumes_attached')) {
                obj['os-extended-volumes:volumes_attached'] = ApiClient.convertToType(data['os-extended-volumes:volumes_attached'], [CloudServerResourceFragmentOsextendedvolumesvolumesAttached]);
            }
            if (data.hasOwnProperty('OS-EXT-SRV-ATTR:hostname')) {
                obj['OS-EXT-SRV-ATTR:hostname'] = ApiClient.convertToType(data['OS-EXT-SRV-ATTR:hostname'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} hostId
 */
CloudServerResourceFragment.prototype['hostId'] = undefined;

/**
 * @member {String} key_name
 */
CloudServerResourceFragment.prototype['key_name'] = undefined;

/**
 * @member {String} OS-EXT-STS:vm_state
 */
CloudServerResourceFragment.prototype['OS-EXT-STS:vm_state'] = undefined;

/**
 * @member {Object} addresses
 */
CloudServerResourceFragment.prototype['addresses'] = undefined;

/**
 * @member {module:model/CloudServerResourceFragmentFlavor} flavor
 */
CloudServerResourceFragment.prototype['flavor'] = undefined;

/**
 * @member {String} OS-EXT-AZ:availability_zone
 */
CloudServerResourceFragment.prototype['OS-EXT-AZ:availability_zone'] = undefined;

/**
 * @member {String} accessIPv4
 */
CloudServerResourceFragment.prototype['accessIPv4'] = undefined;

/**
 * @member {Object} metadata
 */
CloudServerResourceFragment.prototype['metadata'] = undefined;

/**
 * @member {Array.<module:model/CloudServerResourceFragmentOsextendedvolumesvolumesAttached>} os-extended-volumes:volumes_attached
 */
CloudServerResourceFragment.prototype['os-extended-volumes:volumes_attached'] = undefined;

/**
 * @member {String} OS-EXT-SRV-ATTR:hostname
 */
CloudServerResourceFragment.prototype['OS-EXT-SRV-ATTR:hostname'] = undefined;






export default CloudServerResourceFragment;

