/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CloudProviderInfo model module.
 * @module model/CloudProviderInfo
 * @version 0.0.3
 */
class CloudProviderInfo {
    /**
     * Constructs a new <code>CloudProviderInfo</code>.
     * @alias module:model/CloudProviderInfo
     */
    constructor() { 
        
        CloudProviderInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CloudProviderInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CloudProviderInfo} obj Optional instance to populate.
     * @return {module:model/CloudProviderInfo} The populated <code>CloudProviderInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CloudProviderInfo();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ApiClient.convertToType(data['parameters'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CloudProviderInfo.NameEnum} name
 */
CloudProviderInfo.prototype['name'] = undefined;

/**
 * @member {Object} parameters
 */
CloudProviderInfo.prototype['parameters'] = undefined;





/**
 * Allowed values for the <code>name</code> property.
 * @enum {String}
 * @readonly
 */
CloudProviderInfo['NameEnum'] = {

    /**
     * value: "huaweicloud"
     * @const
     */
    "huaweicloud": "huaweicloud"
};



export default CloudProviderInfo;

