/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CloudServerRequestFragmentRootVolume model module.
 * @module model/CloudServerRequestFragmentRootVolume
 * @version 0.0.3
 */
class CloudServerRequestFragmentRootVolume {
    /**
     * Constructs a new <code>CloudServerRequestFragmentRootVolume</code>.
     * @alias module:model/CloudServerRequestFragmentRootVolume
     * @param volumetype {String} 
     */
    constructor(volumetype) { 
        
        CloudServerRequestFragmentRootVolume.initialize(this, volumetype);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, volumetype) { 
        obj['volumetype'] = volumetype;
    }

    /**
     * Constructs a <code>CloudServerRequestFragmentRootVolume</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CloudServerRequestFragmentRootVolume} obj Optional instance to populate.
     * @return {module:model/CloudServerRequestFragmentRootVolume} The populated <code>CloudServerRequestFragmentRootVolume</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CloudServerRequestFragmentRootVolume();

            if (data.hasOwnProperty('volumetype')) {
                obj['volumetype'] = ApiClient.convertToType(data['volumetype'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} volumetype
 */
CloudServerRequestFragmentRootVolume.prototype['volumetype'] = undefined;

/**
 * @member {Number} size
 * @default 1
 */
CloudServerRequestFragmentRootVolume.prototype['size'] = 1;






export default CloudServerRequestFragmentRootVolume;

