/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CloudServerResourceFragmentOsextendedvolumesvolumesAttached model module.
 * @module model/CloudServerResourceFragmentOsextendedvolumesvolumesAttached
 * @version 0.0.3
 */
class CloudServerResourceFragmentOsextendedvolumesvolumesAttached {
    /**
     * Constructs a new <code>CloudServerResourceFragmentOsextendedvolumesvolumesAttached</code>.
     * @alias module:model/CloudServerResourceFragmentOsextendedvolumesvolumesAttached
     */
    constructor() { 
        
        CloudServerResourceFragmentOsextendedvolumesvolumesAttached.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CloudServerResourceFragmentOsextendedvolumesvolumesAttached</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CloudServerResourceFragmentOsextendedvolumesvolumesAttached} obj Optional instance to populate.
     * @return {module:model/CloudServerResourceFragmentOsextendedvolumesvolumesAttached} The populated <code>CloudServerResourceFragmentOsextendedvolumesvolumesAttached</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CloudServerResourceFragmentOsextendedvolumesvolumesAttached();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('delete_on_termination')) {
                obj['delete_on_termination'] = ApiClient.convertToType(data['delete_on_termination'], 'String');
            }
            if (data.hasOwnProperty('boolIndex')) {
                obj['boolIndex'] = ApiClient.convertToType(data['boolIndex'], 'String');
            }
            if (data.hasOwnProperty('device')) {
                obj['device'] = ApiClient.convertToType(data['device'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
CloudServerResourceFragmentOsextendedvolumesvolumesAttached.prototype['id'] = undefined;

/**
 * @member {module:model/CloudServerResourceFragmentOsextendedvolumesvolumesAttached.DeleteOnTerminationEnum} delete_on_termination
 */
CloudServerResourceFragmentOsextendedvolumesvolumesAttached.prototype['delete_on_termination'] = undefined;

/**
 * @member {module:model/CloudServerResourceFragmentOsextendedvolumesvolumesAttached.BoolIndexEnum} boolIndex
 */
CloudServerResourceFragmentOsextendedvolumesvolumesAttached.prototype['boolIndex'] = undefined;

/**
 * @member {String} device
 */
CloudServerResourceFragmentOsextendedvolumesvolumesAttached.prototype['device'] = undefined;





/**
 * Allowed values for the <code>delete_on_termination</code> property.
 * @enum {String}
 * @readonly
 */
CloudServerResourceFragmentOsextendedvolumesvolumesAttached['DeleteOnTerminationEnum'] = {

    /**
     * value: "true"
     * @const
     */
    "true": "true",

    /**
     * value: "false"
     * @const
     */
    "false": "false"
};


/**
 * Allowed values for the <code>boolIndex</code> property.
 * @enum {String}
 * @readonly
 */
CloudServerResourceFragmentOsextendedvolumesvolumesAttached['BoolIndexEnum'] = {

    /**
     * value: "0"
     * @const
     */
    "0": "0",

    /**
     * value: "-1"
     * @const
     */
    "-1": "-1"
};



export default CloudServerResourceFragmentOsextendedvolumesvolumesAttached;

