/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BandwidthResource from './BandwidthResource';

/**
 * The CloudServerRequestFragmentPublicipEip model module.
 * @module model/CloudServerRequestFragmentPublicipEip
 * @version 0.0.3
 */
class CloudServerRequestFragmentPublicipEip {
    /**
     * Constructs a new <code>CloudServerRequestFragmentPublicipEip</code>.
     * @alias module:model/CloudServerRequestFragmentPublicipEip
     * @param ipType {module:model/CloudServerRequestFragmentPublicipEip.IpTypeEnum} 
     * @param bandwidth {module:model/BandwidthResource} 
     */
    constructor(ipType, bandwidth) { 
        
        CloudServerRequestFragmentPublicipEip.initialize(this, ipType, bandwidth);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, ipType, bandwidth) { 
        obj['ip_type'] = ipType;
        obj['bandwidth'] = bandwidth;
    }

    /**
     * Constructs a <code>CloudServerRequestFragmentPublicipEip</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CloudServerRequestFragmentPublicipEip} obj Optional instance to populate.
     * @return {module:model/CloudServerRequestFragmentPublicipEip} The populated <code>CloudServerRequestFragmentPublicipEip</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CloudServerRequestFragmentPublicipEip();

            if (data.hasOwnProperty('ip_type')) {
                obj['ip_type'] = ApiClient.convertToType(data['ip_type'], 'String');
            }
            if (data.hasOwnProperty('bandwidth')) {
                obj['bandwidth'] = BandwidthResource.constructFromObject(data['bandwidth']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CloudServerRequestFragmentPublicipEip.IpTypeEnum} ip_type
 */
CloudServerRequestFragmentPublicipEip.prototype['ip_type'] = undefined;

/**
 * @member {module:model/BandwidthResource} bandwidth
 */
CloudServerRequestFragmentPublicipEip.prototype['bandwidth'] = undefined;





/**
 * Allowed values for the <code>ip_type</code> property.
 * @enum {String}
 * @readonly
 */
CloudServerRequestFragmentPublicipEip['IpTypeEnum'] = {

    /**
     * value: "5_bgp"
     * @const
     */
    "bgp": "5_bgp",

    /**
     * value: "5_sbgp"
     * @const
     */
    "sbgp": "5_sbgp"
};



export default CloudServerRequestFragmentPublicipEip;

