/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CloudServerRequestFragmentPublicipEip from './CloudServerRequestFragmentPublicipEip';

/**
 * The CloudServerRequestFragmentPublicip model module.
 * @module model/CloudServerRequestFragmentPublicip
 * @version 0.0.3
 */
class CloudServerRequestFragmentPublicip {
    /**
     * Constructs a new <code>CloudServerRequestFragmentPublicip</code>.
     * @alias module:model/CloudServerRequestFragmentPublicip
     */
    constructor() { 
        
        CloudServerRequestFragmentPublicip.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CloudServerRequestFragmentPublicip</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CloudServerRequestFragmentPublicip} obj Optional instance to populate.
     * @return {module:model/CloudServerRequestFragmentPublicip} The populated <code>CloudServerRequestFragmentPublicip</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CloudServerRequestFragmentPublicip();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('eip')) {
                obj['eip'] = CloudServerRequestFragmentPublicipEip.constructFromObject(data['eip']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
CloudServerRequestFragmentPublicip.prototype['id'] = undefined;

/**
 * @member {module:model/CloudServerRequestFragmentPublicipEip} eip
 */
CloudServerRequestFragmentPublicip.prototype['eip'] = undefined;






export default CloudServerRequestFragmentPublicip;

