/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CloudProviderInfo from './CloudProviderInfo';
import CloudServerResourceFragment from './CloudServerResourceFragment';

/**
 * The ComputeResourceSpec model module.
 * @module model/ComputeResourceSpec
 * @version 0.0.3
 */
class ComputeResourceSpec {
    /**
     * Constructs a new <code>ComputeResourceSpec</code>.
     * Detailed info that indicates the type of backend cloud storage services.
     * @alias module:model/ComputeResourceSpec
     */
    constructor() { 
        
        ComputeResourceSpec.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ComputeResourceSpec</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ComputeResourceSpec} obj Optional instance to populate.
     * @return {module:model/ComputeResourceSpec} The populated <code>ComputeResourceSpec</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ComputeResourceSpec();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
            if (data.hasOwnProperty('updated')) {
                obj['updated'] = ApiClient.convertToType(data['updated'], 'Date');
            }
            if (data.hasOwnProperty('cloud_provider')) {
                obj['cloud_provider'] = CloudProviderInfo.constructFromObject(data['cloud_provider']);
            }
            if (data.hasOwnProperty('cloud_server_fragment')) {
                obj['cloud_server_fragment'] = CloudServerResourceFragment.constructFromObject(data['cloud_server_fragment']);
            }
            if (data.hasOwnProperty('physical_server_fragment')) {
                obj['physical_server_fragment'] = CloudServerResourceFragment.constructFromObject(data['physical_server_fragment']);
            }
            if (data.hasOwnProperty('pod_fragment')) {
                obj['pod_fragment'] = ApiClient.convertToType(data['pod_fragment'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ComputeResourceSpec.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ComputeResourceSpec.prototype['name'] = undefined;

/**
 * @member {String} description
 */
ComputeResourceSpec.prototype['description'] = undefined;

/**
 * @member {String} status
 */
ComputeResourceSpec.prototype['status'] = undefined;

/**
 * @member {Date} created
 */
ComputeResourceSpec.prototype['created'] = undefined;

/**
 * @member {Date} updated
 */
ComputeResourceSpec.prototype['updated'] = undefined;

/**
 * @member {module:model/CloudProviderInfo} cloud_provider
 */
ComputeResourceSpec.prototype['cloud_provider'] = undefined;

/**
 * @member {module:model/CloudServerResourceFragment} cloud_server_fragment
 */
ComputeResourceSpec.prototype['cloud_server_fragment'] = undefined;

/**
 * @member {module:model/CloudServerResourceFragment} physical_server_fragment
 */
ComputeResourceSpec.prototype['physical_server_fragment'] = undefined;

/**
 * @member {Object} pod_fragment
 */
ComputeResourceSpec.prototype['pod_fragment'] = undefined;






export default ComputeResourceSpec;

