/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CloudProviderInfo from './CloudProviderInfo';
import CloudServerRequestFragment from './CloudServerRequestFragment';

/**
 * The ComputeResourceCreateRequest model module.
 * @module model/ComputeResourceCreateRequest
 * @version 0.0.3
 */
class ComputeResourceCreateRequest {
    /**
     * Constructs a new <code>ComputeResourceCreateRequest</code>.
     * @alias module:model/ComputeResourceCreateRequest
     * @param name {String} 
     * @param availabilityZone {String} 
     * @param cloudProvider {module:model/CloudProviderInfo} 
     */
    constructor(name, availabilityZone, cloudProvider) { 
        
        ComputeResourceCreateRequest.initialize(this, name, availabilityZone, cloudProvider);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, availabilityZone, cloudProvider) { 
        obj['name'] = name;
        obj['availability_zone'] = availabilityZone;
        obj['cloud_provider'] = cloudProvider;
    }

    /**
     * Constructs a <code>ComputeResourceCreateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ComputeResourceCreateRequest} obj Optional instance to populate.
     * @return {module:model/ComputeResourceCreateRequest} The populated <code>ComputeResourceCreateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ComputeResourceCreateRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('availability_zone')) {
                obj['availability_zone'] = ApiClient.convertToType(data['availability_zone'], 'String');
            }
            if (data.hasOwnProperty('cloud_provider')) {
                obj['cloud_provider'] = CloudProviderInfo.constructFromObject(data['cloud_provider']);
            }
            if (data.hasOwnProperty('cloud_server_request_fragment')) {
                obj['cloud_server_request_fragment'] = CloudServerRequestFragment.constructFromObject(data['cloud_server_request_fragment']);
            }
            if (data.hasOwnProperty('physical_server_request_fragment')) {
                obj['physical_server_request_fragment'] = CloudServerRequestFragment.constructFromObject(data['physical_server_request_fragment']);
            }
            if (data.hasOwnProperty('pod_request_fragment')) {
                obj['pod_request_fragment'] = ApiClient.convertToType(data['pod_request_fragment'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
ComputeResourceCreateRequest.prototype['name'] = undefined;

/**
 * @member {String} description
 */
ComputeResourceCreateRequest.prototype['description'] = undefined;

/**
 * @member {String} availability_zone
 */
ComputeResourceCreateRequest.prototype['availability_zone'] = undefined;

/**
 * @member {module:model/CloudProviderInfo} cloud_provider
 */
ComputeResourceCreateRequest.prototype['cloud_provider'] = undefined;

/**
 * @member {module:model/CloudServerRequestFragment} cloud_server_request_fragment
 */
ComputeResourceCreateRequest.prototype['cloud_server_request_fragment'] = undefined;

/**
 * @member {module:model/CloudServerRequestFragment} physical_server_request_fragment
 */
ComputeResourceCreateRequest.prototype['physical_server_request_fragment'] = undefined;

/**
 * @member {Object} pod_request_fragment
 */
ComputeResourceCreateRequest.prototype['pod_request_fragment'] = undefined;






export default ComputeResourceCreateRequest;

