/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FileShareResourceFragmentExportLocations model module.
 * @module model/FileShareResourceFragmentExportLocations
 * @version 0.0.3
 */
class FileShareResourceFragmentExportLocations {
    /**
     * Constructs a new <code>FileShareResourceFragmentExportLocations</code>.
     * @alias module:model/FileShareResourceFragmentExportLocations
     */
    constructor() { 
        
        FileShareResourceFragmentExportLocations.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FileShareResourceFragmentExportLocations</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FileShareResourceFragmentExportLocations} obj Optional instance to populate.
     * @return {module:model/FileShareResourceFragmentExportLocations} The populated <code>FileShareResourceFragmentExportLocations</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FileShareResourceFragmentExportLocations();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('share_instance_id')) {
                obj['share_instance_id'] = ApiClient.convertToType(data['share_instance_id'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('preferred')) {
                obj['preferred'] = ApiClient.convertToType(data['preferred'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
FileShareResourceFragmentExportLocations.prototype['id'] = undefined;

/**
 * @member {String} share_instance_id
 */
FileShareResourceFragmentExportLocations.prototype['share_instance_id'] = undefined;

/**
 * @member {String} path
 */
FileShareResourceFragmentExportLocations.prototype['path'] = undefined;

/**
 * @member {Boolean} preferred
 */
FileShareResourceFragmentExportLocations.prototype['preferred'] = undefined;






export default FileShareResourceFragmentExportLocations;

