/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FileShareRequestFragment model module.
 * @module model/FileShareRequestFragment
 * @version 0.0.3
 */
class FileShareRequestFragment {
    /**
     * Constructs a new <code>FileShareRequestFragment</code>.
     * @alias module:model/FileShareRequestFragment
     * @param shareProto {String} 
     */
    constructor(shareProto) { 
        
        FileShareRequestFragment.initialize(this, shareProto);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, shareProto) { 
        obj['share_proto'] = shareProto;
    }

    /**
     * Constructs a <code>FileShareRequestFragment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FileShareRequestFragment} obj Optional instance to populate.
     * @return {module:model/FileShareRequestFragment} The populated <code>FileShareRequestFragment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FileShareRequestFragment();

            if (data.hasOwnProperty('share_proto')) {
                obj['share_proto'] = ApiClient.convertToType(data['share_proto'], 'String');
            }
            if (data.hasOwnProperty('share_type')) {
                obj['share_type'] = ApiClient.convertToType(data['share_type'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
            if (data.hasOwnProperty('share_network_id')) {
                obj['share_network_id'] = ApiClient.convertToType(data['share_network_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} share_proto
 */
FileShareRequestFragment.prototype['share_proto'] = undefined;

/**
 * @member {String} share_type
 */
FileShareRequestFragment.prototype['share_type'] = undefined;

/**
 * @member {Object} metadata
 */
FileShareRequestFragment.prototype['metadata'] = undefined;

/**
 * @member {String} share_network_id
 */
FileShareRequestFragment.prototype['share_network_id'] = undefined;






export default FileShareRequestFragment;

