/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CloudProviderInfo from './CloudProviderInfo';
import PublicipRequestFragment from './PublicipRequestFragment';
import SubnetRequestFragment from './SubnetRequestFragment';

/**
 * The NetworkResourceCreateRequest model module.
 * @module model/NetworkResourceCreateRequest
 * @version 0.0.3
 */
class NetworkResourceCreateRequest {
    /**
     * Constructs a new <code>NetworkResourceCreateRequest</code>.
     * @alias module:model/NetworkResourceCreateRequest
     * @param cloudProvider {module:model/CloudProviderInfo} 
     * @param name {String} 
     */
    constructor(cloudProvider, name) { 
        
        NetworkResourceCreateRequest.initialize(this, cloudProvider, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cloudProvider, name) { 
        obj['cloud_provider'] = cloudProvider;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>NetworkResourceCreateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NetworkResourceCreateRequest} obj Optional instance to populate.
     * @return {module:model/NetworkResourceCreateRequest} The populated <code>NetworkResourceCreateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetworkResourceCreateRequest();

            if (data.hasOwnProperty('cloud_provider')) {
                obj['cloud_provider'] = CloudProviderInfo.constructFromObject(data['cloud_provider']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('vpc_request_fragment')) {
                obj['vpc_request_fragment'] = SubnetRequestFragment.constructFromObject(data['vpc_request_fragment']);
            }
            if (data.hasOwnProperty('subnet_request_fragment')) {
                obj['subnet_request_fragment'] = SubnetRequestFragment.constructFromObject(data['subnet_request_fragment']);
            }
            if (data.hasOwnProperty('publicip_request_fragment')) {
                obj['publicip_request_fragment'] = PublicipRequestFragment.constructFromObject(data['publicip_request_fragment']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CloudProviderInfo} cloud_provider
 */
NetworkResourceCreateRequest.prototype['cloud_provider'] = undefined;

/**
 * @member {String} name
 */
NetworkResourceCreateRequest.prototype['name'] = undefined;

/**
 * @member {String} description
 */
NetworkResourceCreateRequest.prototype['description'] = undefined;

/**
 * @member {module:model/SubnetRequestFragment} vpc_request_fragment
 */
NetworkResourceCreateRequest.prototype['vpc_request_fragment'] = undefined;

/**
 * @member {module:model/SubnetRequestFragment} subnet_request_fragment
 */
NetworkResourceCreateRequest.prototype['subnet_request_fragment'] = undefined;

/**
 * @member {module:model/PublicipRequestFragment} publicip_request_fragment
 */
NetworkResourceCreateRequest.prototype['publicip_request_fragment'] = undefined;






export default NetworkResourceCreateRequest;

