/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CloudProviderInfo from './CloudProviderInfo';
import PublicipResourceFragment from './PublicipResourceFragment';
import SubnetResourceFragment from './SubnetResourceFragment';
import VPCResourceFragment from './VPCResourceFragment';

/**
 * The NetworkResourceSpec model module.
 * @module model/NetworkResourceSpec
 * @version 0.0.3
 */
class NetworkResourceSpec {
    /**
     * Constructs a new <code>NetworkResourceSpec</code>.
     * Detailed info that indicates the type of backend cloud network services.
     * @alias module:model/NetworkResourceSpec
     */
    constructor() { 
        
        NetworkResourceSpec.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NetworkResourceSpec</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NetworkResourceSpec} obj Optional instance to populate.
     * @return {module:model/NetworkResourceSpec} The populated <code>NetworkResourceSpec</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetworkResourceSpec();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('cloud_provider')) {
                obj['cloud_provider'] = CloudProviderInfo.constructFromObject(data['cloud_provider']);
            }
            if (data.hasOwnProperty('vpc_fragment')) {
                obj['vpc_fragment'] = VPCResourceFragment.constructFromObject(data['vpc_fragment']);
            }
            if (data.hasOwnProperty('subnet_fragment')) {
                obj['subnet_fragment'] = SubnetResourceFragment.constructFromObject(data['subnet_fragment']);
            }
            if (data.hasOwnProperty('publicip_fragment')) {
                obj['publicip_fragment'] = PublicipResourceFragment.constructFromObject(data['publicip_fragment']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
NetworkResourceSpec.prototype['id'] = undefined;

/**
 * @member {String} name
 */
NetworkResourceSpec.prototype['name'] = undefined;

/**
 * @member {String} status
 */
NetworkResourceSpec.prototype['status'] = undefined;

/**
 * @member {module:model/CloudProviderInfo} cloud_provider
 */
NetworkResourceSpec.prototype['cloud_provider'] = undefined;

/**
 * @member {module:model/VPCResourceFragment} vpc_fragment
 */
NetworkResourceSpec.prototype['vpc_fragment'] = undefined;

/**
 * @member {module:model/SubnetResourceFragment} subnet_fragment
 */
NetworkResourceSpec.prototype['subnet_fragment'] = undefined;

/**
 * @member {module:model/PublicipResourceFragment} publicip_fragment
 */
NetworkResourceSpec.prototype['publicip_fragment'] = undefined;






export default NetworkResourceSpec;

