/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PublicipResourceFragment model module.
 * @module model/PublicipResourceFragment
 * @version 0.0.3
 */
class PublicipResourceFragment {
    /**
     * Constructs a new <code>PublicipResourceFragment</code>.
     * @alias module:model/PublicipResourceFragment
     */
    constructor() { 
        
        PublicipResourceFragment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PublicipResourceFragment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PublicipResourceFragment} obj Optional instance to populate.
     * @return {module:model/PublicipResourceFragment} The populated <code>PublicipResourceFragment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PublicipResourceFragment();

            if (data.hasOwnProperty('profile')) {
                obj['profile'] = ApiClient.convertToType(data['profile'], Object);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('public_ip_address')) {
                obj['public_ip_address'] = ApiClient.convertToType(data['public_ip_address'], 'String');
            }
            if (data.hasOwnProperty('private_ip_address')) {
                obj['private_ip_address'] = ApiClient.convertToType(data['private_ip_address'], 'String');
            }
            if (data.hasOwnProperty('port_id')) {
                obj['port_id'] = ApiClient.convertToType(data['port_id'], 'String');
            }
            if (data.hasOwnProperty('create_time')) {
                obj['create_time'] = ApiClient.convertToType(data['create_time'], 'Date');
            }
            if (data.hasOwnProperty('bandwidth_id')) {
                obj['bandwidth_id'] = ApiClient.convertToType(data['bandwidth_id'], 'String');
            }
            if (data.hasOwnProperty('bandwidth_share_type')) {
                obj['bandwidth_share_type'] = ApiClient.convertToType(data['bandwidth_share_type'], 'String');
            }
            if (data.hasOwnProperty('bandwidth_size')) {
                obj['bandwidth_size'] = ApiClient.convertToType(data['bandwidth_size'], 'Number');
            }
            if (data.hasOwnProperty('bandwidth_name')) {
                obj['bandwidth_name'] = ApiClient.convertToType(data['bandwidth_name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Object} profile
 */
PublicipResourceFragment.prototype['profile'] = undefined;

/**
 * @member {String} type
 */
PublicipResourceFragment.prototype['type'] = undefined;

/**
 * @member {String} public_ip_address
 */
PublicipResourceFragment.prototype['public_ip_address'] = undefined;

/**
 * @member {String} private_ip_address
 */
PublicipResourceFragment.prototype['private_ip_address'] = undefined;

/**
 * @member {String} port_id
 */
PublicipResourceFragment.prototype['port_id'] = undefined;

/**
 * @member {Date} create_time
 */
PublicipResourceFragment.prototype['create_time'] = undefined;

/**
 * @member {String} bandwidth_id
 */
PublicipResourceFragment.prototype['bandwidth_id'] = undefined;

/**
 * @member {String} bandwidth_share_type
 */
PublicipResourceFragment.prototype['bandwidth_share_type'] = undefined;

/**
 * @member {Number} bandwidth_size
 */
PublicipResourceFragment.prototype['bandwidth_size'] = undefined;

/**
 * @member {String} bandwidth_name
 */
PublicipResourceFragment.prototype['bandwidth_name'] = undefined;






export default PublicipResourceFragment;

