/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BandwidthResource from './BandwidthResource';
import PublicipRequestFragmentPublicip from './PublicipRequestFragmentPublicip';

/**
 * The PublicipRequestFragment model module.
 * @module model/PublicipRequestFragment
 * @version 0.0.3
 */
class PublicipRequestFragment {
    /**
     * Constructs a new <code>PublicipRequestFragment</code>.
     * @alias module:model/PublicipRequestFragment
     * @param publicip {module:model/PublicipRequestFragmentPublicip} 
     * @param bandwidth {module:model/BandwidthResource} 
     */
    constructor(publicip, bandwidth) { 
        
        PublicipRequestFragment.initialize(this, publicip, bandwidth);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, publicip, bandwidth) { 
        obj['publicip'] = publicip;
        obj['bandwidth'] = bandwidth;
    }

    /**
     * Constructs a <code>PublicipRequestFragment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PublicipRequestFragment} obj Optional instance to populate.
     * @return {module:model/PublicipRequestFragment} The populated <code>PublicipRequestFragment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PublicipRequestFragment();

            if (data.hasOwnProperty('publicip')) {
                obj['publicip'] = PublicipRequestFragmentPublicip.constructFromObject(data['publicip']);
            }
            if (data.hasOwnProperty('bandwidth')) {
                obj['bandwidth'] = BandwidthResource.constructFromObject(data['bandwidth']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/PublicipRequestFragmentPublicip} publicip
 */
PublicipRequestFragment.prototype['publicip'] = undefined;

/**
 * @member {module:model/BandwidthResource} bandwidth
 */
PublicipRequestFragment.prototype['bandwidth'] = undefined;






export default PublicipRequestFragment;

