/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PublicipRequestFragmentPublicip model module.
 * @module model/PublicipRequestFragmentPublicip
 * @version 0.0.3
 */
class PublicipRequestFragmentPublicip {
    /**
     * Constructs a new <code>PublicipRequestFragmentPublicip</code>.
     * @alias module:model/PublicipRequestFragmentPublicip
     * @param type {String} 
     */
    constructor(type) { 
        
        PublicipRequestFragmentPublicip.initialize(this, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type) { 
        obj['type'] = type;
    }

    /**
     * Constructs a <code>PublicipRequestFragmentPublicip</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PublicipRequestFragmentPublicip} obj Optional instance to populate.
     * @return {module:model/PublicipRequestFragmentPublicip} The populated <code>PublicipRequestFragmentPublicip</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PublicipRequestFragmentPublicip();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('ip_address')) {
                obj['ip_address'] = ApiClient.convertToType(data['ip_address'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} type
 */
PublicipRequestFragmentPublicip.prototype['type'] = undefined;

/**
 * @member {String} ip_address
 */
PublicipRequestFragmentPublicip.prototype['ip_address'] = undefined;






export default PublicipRequestFragmentPublicip;

