/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BackupResourceFragment from './BackupResourceFragment';
import BlockVolumeResourceFragment from './BlockVolumeResourceFragment';
import CloudProviderInfo from './CloudProviderInfo';
import FileShareResourceFragment from './FileShareResourceFragment';

/**
 * The StorageResourceSpec model module.
 * @module model/StorageResourceSpec
 * @version 0.0.3
 */
class StorageResourceSpec {
    /**
     * Constructs a new <code>StorageResourceSpec</code>.
     * Detailed info that indicates the type of backend cloud storage services.
     * @alias module:model/StorageResourceSpec
     */
    constructor() { 
        
        StorageResourceSpec.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StorageResourceSpec</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StorageResourceSpec} obj Optional instance to populate.
     * @return {module:model/StorageResourceSpec} The populated <code>StorageResourceSpec</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StorageResourceSpec();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('cloud_provider')) {
                obj['cloud_provider'] = CloudProviderInfo.constructFromObject(data['cloud_provider']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('availability_zone')) {
                obj['availability_zone'] = ApiClient.convertToType(data['availability_zone'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('block_volume_fragment')) {
                obj['block_volume_fragment'] = BlockVolumeResourceFragment.constructFromObject(data['block_volume_fragment']);
            }
            if (data.hasOwnProperty('file_share_fragment')) {
                obj['file_share_fragment'] = FileShareResourceFragment.constructFromObject(data['file_share_fragment']);
            }
            if (data.hasOwnProperty('backup_fragment')) {
                obj['backup_fragment'] = BackupResourceFragment.constructFromObject(data['backup_fragment']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
StorageResourceSpec.prototype['id'] = undefined;

/**
 * @member {String} name
 */
StorageResourceSpec.prototype['name'] = undefined;

/**
 * @member {String} description
 */
StorageResourceSpec.prototype['description'] = undefined;

/**
 * @member {Date} created_at
 */
StorageResourceSpec.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
StorageResourceSpec.prototype['updated_at'] = undefined;

/**
 * @member {module:model/CloudProviderInfo} cloud_provider
 */
StorageResourceSpec.prototype['cloud_provider'] = undefined;

/**
 * @member {String} status
 */
StorageResourceSpec.prototype['status'] = undefined;

/**
 * @member {String} availability_zone
 */
StorageResourceSpec.prototype['availability_zone'] = undefined;

/**
 * @member {Number} size
 */
StorageResourceSpec.prototype['size'] = undefined;

/**
 * @member {module:model/BlockVolumeResourceFragment} block_volume_fragment
 */
StorageResourceSpec.prototype['block_volume_fragment'] = undefined;

/**
 * @member {module:model/FileShareResourceFragment} file_share_fragment
 */
StorageResourceSpec.prototype['file_share_fragment'] = undefined;

/**
 * @member {module:model/BackupResourceFragment} backup_fragment
 */
StorageResourceSpec.prototype['backup_fragment'] = undefined;






export default StorageResourceSpec;

