/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BackupRequestFragment from './BackupRequestFragment';
import BlockVolumeRequestFragment from './BlockVolumeRequestFragment';
import CloudProviderInfo from './CloudProviderInfo';
import FileShareRequestFragment from './FileShareRequestFragment';

/**
 * The StorageResourceCreateRequest model module.
 * @module model/StorageResourceCreateRequest
 * @version 0.0.3
 */
class StorageResourceCreateRequest {
    /**
     * Constructs a new <code>StorageResourceCreateRequest</code>.
     * @alias module:model/StorageResourceCreateRequest
     * @param cloudProvider {module:model/CloudProviderInfo} 
     * @param availabilityZone {String} 
     * @param name {String} 
     * @param size {Number} 
     */
    constructor(cloudProvider, availabilityZone, name, size) { 
        
        StorageResourceCreateRequest.initialize(this, cloudProvider, availabilityZone, name, size);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cloudProvider, availabilityZone, name, size) { 
        obj['cloud_provider'] = cloudProvider;
        obj['availability_zone'] = availabilityZone;
        obj['name'] = name;
        obj['size'] = size;
    }

    /**
     * Constructs a <code>StorageResourceCreateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StorageResourceCreateRequest} obj Optional instance to populate.
     * @return {module:model/StorageResourceCreateRequest} The populated <code>StorageResourceCreateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StorageResourceCreateRequest();

            if (data.hasOwnProperty('cloud_provider')) {
                obj['cloud_provider'] = CloudProviderInfo.constructFromObject(data['cloud_provider']);
            }
            if (data.hasOwnProperty('availability_zone')) {
                obj['availability_zone'] = ApiClient.convertToType(data['availability_zone'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('block_volume_request_fragment')) {
                obj['block_volume_request_fragment'] = BlockVolumeRequestFragment.constructFromObject(data['block_volume_request_fragment']);
            }
            if (data.hasOwnProperty('file_share_request_fragment')) {
                obj['file_share_request_fragment'] = FileShareRequestFragment.constructFromObject(data['file_share_request_fragment']);
            }
            if (data.hasOwnProperty('backup_request_fragment')) {
                obj['backup_request_fragment'] = BackupRequestFragment.constructFromObject(data['backup_request_fragment']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CloudProviderInfo} cloud_provider
 */
StorageResourceCreateRequest.prototype['cloud_provider'] = undefined;

/**
 * @member {String} availability_zone
 */
StorageResourceCreateRequest.prototype['availability_zone'] = undefined;

/**
 * @member {String} name
 */
StorageResourceCreateRequest.prototype['name'] = undefined;

/**
 * @member {String} description
 */
StorageResourceCreateRequest.prototype['description'] = undefined;

/**
 * @member {Number} size
 */
StorageResourceCreateRequest.prototype['size'] = undefined;

/**
 * @member {module:model/BlockVolumeRequestFragment} block_volume_request_fragment
 */
StorageResourceCreateRequest.prototype['block_volume_request_fragment'] = undefined;

/**
 * @member {module:model/FileShareRequestFragment} file_share_request_fragment
 */
StorageResourceCreateRequest.prototype['file_share_request_fragment'] = undefined;

/**
 * @member {module:model/BackupRequestFragment} backup_request_fragment
 */
StorageResourceCreateRequest.prototype['backup_request_fragment'] = undefined;






export default StorageResourceCreateRequest;

