/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SubnetResourceFragment model module.
 * @module model/SubnetResourceFragment
 * @version 0.0.3
 */
class SubnetResourceFragment {
    /**
     * Constructs a new <code>SubnetResourceFragment</code>.
     * @alias module:model/SubnetResourceFragment
     */
    constructor() { 
        
        SubnetResourceFragment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SubnetResourceFragment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubnetResourceFragment} obj Optional instance to populate.
     * @return {module:model/SubnetResourceFragment} The populated <code>SubnetResourceFragment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubnetResourceFragment();

            if (data.hasOwnProperty('cidr')) {
                obj['cidr'] = ApiClient.convertToType(data['cidr'], 'String');
            }
            if (data.hasOwnProperty('gateway_ip')) {
                obj['gateway_ip'] = ApiClient.convertToType(data['gateway_ip'], 'String');
            }
            if (data.hasOwnProperty('vpc_id')) {
                obj['vpc_id'] = ApiClient.convertToType(data['vpc_id'], 'String');
            }
            if (data.hasOwnProperty('dhcp_enable')) {
                obj['dhcp_enable'] = ApiClient.convertToType(data['dhcp_enable'], 'Boolean');
            }
            if (data.hasOwnProperty('primary_dns')) {
                obj['primary_dns'] = ApiClient.convertToType(data['primary_dns'], 'String');
            }
            if (data.hasOwnProperty('availability_zone')) {
                obj['availability_zone'] = ApiClient.convertToType(data['availability_zone'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} cidr
 */
SubnetResourceFragment.prototype['cidr'] = undefined;

/**
 * @member {String} gateway_ip
 */
SubnetResourceFragment.prototype['gateway_ip'] = undefined;

/**
 * @member {String} vpc_id
 */
SubnetResourceFragment.prototype['vpc_id'] = undefined;

/**
 * @member {Boolean} dhcp_enable
 */
SubnetResourceFragment.prototype['dhcp_enable'] = undefined;

/**
 * @member {String} primary_dns
 */
SubnetResourceFragment.prototype['primary_dns'] = undefined;

/**
 * @member {String} availability_zone
 */
SubnetResourceFragment.prototype['availability_zone'] = undefined;






export default SubnetResourceFragment;

