/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SubnetRequestFragment model module.
 * @module model/SubnetRequestFragment
 * @version 0.0.3
 */
class SubnetRequestFragment {
    /**
     * Constructs a new <code>SubnetRequestFragment</code>.
     * @alias module:model/SubnetRequestFragment
     * @param name {String} 
     * @param cidr {String} 
     * @param gatewayIp {String} 
     * @param vpcId {String} 
     */
    constructor(name, cidr, gatewayIp, vpcId) { 
        
        SubnetRequestFragment.initialize(this, name, cidr, gatewayIp, vpcId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, cidr, gatewayIp, vpcId) { 
        obj['name'] = name;
        obj['cidr'] = cidr;
        obj['gateway_ip'] = gatewayIp;
        obj['vpc_id'] = vpcId;
    }

    /**
     * Constructs a <code>SubnetRequestFragment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubnetRequestFragment} obj Optional instance to populate.
     * @return {module:model/SubnetRequestFragment} The populated <code>SubnetRequestFragment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubnetRequestFragment();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('cidr')) {
                obj['cidr'] = ApiClient.convertToType(data['cidr'], 'String');
            }
            if (data.hasOwnProperty('gateway_ip')) {
                obj['gateway_ip'] = ApiClient.convertToType(data['gateway_ip'], 'String');
            }
            if (data.hasOwnProperty('vpc_id')) {
                obj['vpc_id'] = ApiClient.convertToType(data['vpc_id'], 'String');
            }
            if (data.hasOwnProperty('dhcp_enable')) {
                obj['dhcp_enable'] = ApiClient.convertToType(data['dhcp_enable'], 'Boolean');
            }
            if (data.hasOwnProperty('primary_dns')) {
                obj['primary_dns'] = ApiClient.convertToType(data['primary_dns'], 'String');
            }
            if (data.hasOwnProperty('availability_zone')) {
                obj['availability_zone'] = ApiClient.convertToType(data['availability_zone'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
SubnetRequestFragment.prototype['name'] = undefined;

/**
 * @member {String} cidr
 */
SubnetRequestFragment.prototype['cidr'] = undefined;

/**
 * @member {String} gateway_ip
 */
SubnetRequestFragment.prototype['gateway_ip'] = undefined;

/**
 * @member {String} vpc_id
 */
SubnetRequestFragment.prototype['vpc_id'] = undefined;

/**
 * @member {Boolean} dhcp_enable
 * @default true
 */
SubnetRequestFragment.prototype['dhcp_enable'] = true;

/**
 * @member {String} primary_dns
 */
SubnetRequestFragment.prototype['primary_dns'] = undefined;

/**
 * @member {String} availability_zone
 */
SubnetRequestFragment.prototype['availability_zone'] = undefined;






export default SubnetRequestFragment;

