/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VPCRequestFragment model module.
 * @module model/VPCRequestFragment
 * @version 0.0.3
 */
class VPCRequestFragment {
    /**
     * Constructs a new <code>VPCRequestFragment</code>.
     * @alias module:model/VPCRequestFragment
     */
    constructor() { 
        
        VPCRequestFragment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VPCRequestFragment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VPCRequestFragment} obj Optional instance to populate.
     * @return {module:model/VPCRequestFragment} The populated <code>VPCRequestFragment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VPCRequestFragment();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('cidr')) {
                obj['cidr'] = ApiClient.convertToType(data['cidr'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
VPCRequestFragment.prototype['name'] = undefined;

/**
 * @member {String} cidr
 */
VPCRequestFragment.prototype['cidr'] = undefined;






export default VPCRequestFragment;

