/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VPCResourceFragmentRoutes from './VPCResourceFragmentRoutes';

/**
 * The VPCResourceFragment model module.
 * @module model/VPCResourceFragment
 * @version 0.0.3
 */
class VPCResourceFragment {
    /**
     * Constructs a new <code>VPCResourceFragment</code>.
     * @alias module:model/VPCResourceFragment
     */
    constructor() { 
        
        VPCResourceFragment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VPCResourceFragment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VPCResourceFragment} obj Optional instance to populate.
     * @return {module:model/VPCResourceFragment} The populated <code>VPCResourceFragment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VPCResourceFragment();

            if (data.hasOwnProperty('cidr')) {
                obj['cidr'] = ApiClient.convertToType(data['cidr'], 'String');
            }
            if (data.hasOwnProperty('routes')) {
                obj['routes'] = ApiClient.convertToType(data['routes'], [VPCResourceFragmentRoutes]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} cidr
 */
VPCResourceFragment.prototype['cidr'] = undefined;

/**
 * @member {Array.<module:model/VPCResourceFragmentRoutes>} routes
 */
VPCResourceFragment.prototype['routes'] = undefined;






export default VPCResourceFragment;

