/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * API version: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BlockVolumeResourceFragmentAttachments struct {
	Id string `json:"id,omitempty"`

	ServerId string `json:"server_id,omitempty"`

	VolumeId string `json:"volume_id,omitempty"`

	AttachmentId string `json:"attachment_id,omitempty"`

	Device string `json:"device,omitempty"`

	HostName string `json:"host_name,omitempty"`
}
