/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * API version: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CloudServerResourceFragmentFlavor struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Disk string `json:"disk,omitempty"`

	Vcpus string `json:"vcpus,omitempty"`

	Ram string `json:"ram,omitempty"`
}
