/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * API version: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// ComputeResourceSpec - Detailed info that indicates the type of backend cloud storage services.
type ComputeResourceSpec struct {
	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	Status string `json:"status,omitempty"`

	Created time.Time `json:"created,omitempty"`

	Updated time.Time `json:"updated,omitempty"`

	CloudProvider CloudProviderInfo `json:"cloud_provider,omitempty"`

	CloudServerFragment CloudServerResourceFragment `json:"cloud_server_fragment,omitempty"`

	PhysicalServerFragment CloudServerResourceFragment `json:"physical_server_fragment,omitempty"`

	PodFragment map[string]interface{} `json:"pod_fragment,omitempty"`
}
