/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * API version: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FileShareResourceFragment struct {
	ShareServerId string `json:"share_server_id,omitempty"`

	ShareNetworkId string `json:"share_network_id,omitempty"`

	Metadata map[string]interface{} `json:"metadata,omitempty"`

	Host string `json:"host,omitempty"`

	ShareProto string `json:"share_proto,omitempty"`

	ShareTypeName string `json:"share_type_name,omitempty"`

	ShareType string `json:"share_type,omitempty"`

	ExportLocations []FileShareResourceFragmentExportLocations `json:"export_locations,omitempty"`
}
