/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * API version: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BlockVolumeResourceFragment struct {
	VolumeType string `json:"volume_type,omitempty"`

	Metadata map[string]interface{} `json:"metadata,omitempty"`

	OsVolHostAttrhost string `json:"os-vol-host-attr:host,omitempty"`

	Multiattach bool `json:"multiattach,omitempty"`

	DedicatedStorageId string `json:"dedicated_storage_id,omitempty"`

	DedicatedStorageName string `json:"dedicated_storage_name,omitempty"`

	Tags map[string]interface{} `json:"tags,omitempty"`

	Attachments []BlockVolumeResourceFragmentAttachments `json:"attachments,omitempty"`
}
