/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * API version: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FileShareResourceFragmentExportLocations struct {
	Id string `json:"id,omitempty"`

	ShareInstanceId string `json:"share_instance_id,omitempty"`

	Path string `json:"path,omitempty"`

	Preferred bool `json:"preferred,omitempty"`
}
