/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * API version: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ComputeResourceCreateRequest struct {

	Name string `json:"name"`

	Description string `json:"description,omitempty"`

	AvailabilityZone string `json:"availability_zone"`

	CloudProvider CloudProviderInfo `json:"cloud_provider"`

	CloudServerRequestFragment CloudServerRequestFragment `json:"cloud_server_request_fragment,omitempty"`

	PhysicalServerRequestFragment CloudServerRequestFragment `json:"physical_server_request_fragment,omitempty"`

	PodRequestFragment map[string]interface{} `json:"pod_request_fragment,omitempty"`
}
