/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * API version: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type PublicipResourceFragment struct {

	Profile map[string]interface{} `json:"profile,omitempty"`

	Type string `json:"type,omitempty"`

	PublicIpAddress string `json:"public_ip_address,omitempty"`

	PrivateIpAddress string `json:"private_ip_address,omitempty"`

	PortId string `json:"port_id,omitempty"`

	CreateTime time.Time `json:"create_time,omitempty"`

	BandwidthId string `json:"bandwidth_id,omitempty"`

	BandwidthShareType string `json:"bandwidth_share_type,omitempty"`

	BandwidthSize int32 `json:"bandwidth_size,omitempty"`

	BandwidthName string `json:"bandwidth_name,omitempty"`
}
