/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * API version: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NetworkResourceSpec - Detailed info that indicates the type of backend cloud network services.
type NetworkResourceSpec struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Status string `json:"status,omitempty"`

	CloudProvider CloudProviderInfo `json:"cloud_provider,omitempty"`

	VpcFragment VpcResourceFragment `json:"vpc_fragment,omitempty"`

	SubnetFragment SubnetResourceFragment `json:"subnet_fragment,omitempty"`

	PublicipFragment PublicipResourceFragment `json:"publicip_fragment,omitempty"`
}
