/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * API version: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CloudServerResourceFragmentOsextendedvolumesvolumesAttached struct {

	Id string `json:"id,omitempty"`

	DeleteOnTermination string `json:"delete_on_termination,omitempty"`

	BoolIndex string `json:"boolIndex,omitempty"`

	Device string `json:"device,omitempty"`
}
