/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * API version: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ErrorSpec - Detailed HTTP error response, which consists of a HTTP status code, and a custom error message unique for each failure case.
type ErrorSpec struct {
	Code int32 `json:"code"`

	Message string `json:"message"`
}
