/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * API version: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type StorageResourceCreateRequest struct {
	CloudProvider CloudProviderInfo `json:"cloud_provider"`

	AvailabilityZone string `json:"availability_zone"`

	Name string `json:"name"`

	Description string `json:"description,omitempty"`

	Size int32 `json:"size"`

	BlockVolumeRequestFragment BlockVolumeRequestFragment `json:"block_volume_request_fragment,omitempty"`

	FileShareRequestFragment FileShareRequestFragment `json:"file_share_request_fragment,omitempty"`

	BackupRequestFragment BackupRequestFragment `json:"backup_request_fragment,omitempty"`
}
