/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * API version: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SubnetResourceFragment struct {
	Cidr string `json:"cidr,omitempty"`

	GatewayIp string `json:"gateway_ip,omitempty"`

	VpcId string `json:"vpc_id,omitempty"`

	DhcpEnable bool `json:"dhcp_enable,omitempty"`

	PrimaryDns string `json:"primary_dns,omitempty"`

	AvailabilityZone string `json:"availability_zone,omitempty"`
}
