/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockVolumeResourceFragmentAttachments {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "server_id", skip_serializing_if = "Option::is_none")]
    pub server_id: Option<String>,
    #[serde(rename = "volume_id", skip_serializing_if = "Option::is_none")]
    pub volume_id: Option<String>,
    #[serde(rename = "attachment_id", skip_serializing_if = "Option::is_none")]
    pub attachment_id: Option<String>,
    #[serde(rename = "device", skip_serializing_if = "Option::is_none")]
    pub device: Option<String>,
    #[serde(rename = "host_name", skip_serializing_if = "Option::is_none")]
    pub host_name: Option<String>,
}

impl BlockVolumeResourceFragmentAttachments {
    pub fn new() -> BlockVolumeResourceFragmentAttachments {
        BlockVolumeResourceFragmentAttachments {
            id: None,
            server_id: None,
            volume_id: None,
            attachment_id: None,
            device: None,
            host_name: None,
        }
    }
}


