/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudServerResourceFragmentFlavor {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "disk", skip_serializing_if = "Option::is_none")]
    pub disk: Option<String>,
    #[serde(rename = "vcpus", skip_serializing_if = "Option::is_none")]
    pub vcpus: Option<String>,
    #[serde(rename = "ram", skip_serializing_if = "Option::is_none")]
    pub ram: Option<String>,
}

impl CloudServerResourceFragmentFlavor {
    pub fn new() -> CloudServerResourceFragmentFlavor {
        CloudServerResourceFragmentFlavor {
            id: None,
            name: None,
            disk: None,
            vcpus: None,
            ram: None,
        }
    }
}


