/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudServerRequestFragmentPublicip {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "eip", skip_serializing_if = "Option::is_none")]
    pub eip: Option<crate::models::CloudServerRequestFragmentPublicipEip>,
}

impl CloudServerRequestFragmentPublicip {
    pub fn new() -> CloudServerRequestFragmentPublicip {
        CloudServerRequestFragmentPublicip {
            id: None,
            eip: None,
        }
    }
}


