/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct ComputeResourceCreateRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "availability_zone")]
    pub availability_zone: String,
    #[serde(rename = "cloud_provider")]
    pub cloud_provider: crate::models::CloudProviderInfo,
    #[serde(rename = "cloud_server_request_fragment", skip_serializing_if = "Option::is_none")]
    pub cloud_server_request_fragment: Option<crate::models::CloudServerRequestFragment>,
    #[serde(rename = "physical_server_request_fragment", skip_serializing_if = "Option::is_none")]
    pub physical_server_request_fragment: Option<crate::models::CloudServerRequestFragment>,
    #[serde(rename = "pod_request_fragment", skip_serializing_if = "Option::is_none")]
    pub pod_request_fragment: Option<serde_json::Value>,
}

impl ComputeResourceCreateRequest {
    pub fn new(name: String, availability_zone: String, cloud_provider: crate::models::CloudProviderInfo) -> ComputeResourceCreateRequest {
        ComputeResourceCreateRequest {
            name: name,
            description: None,
            availability_zone: availability_zone,
            cloud_provider: cloud_provider,
            cloud_server_request_fragment: None,
            physical_server_request_fragment: None,
            pod_request_fragment: None,
        }
    }
}


