/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct VpcResourceFragmentRoutes {
    #[serde(rename = "destination", skip_serializing_if = "Option::is_none")]
    pub destination: Option<String>,
    #[serde(rename = "nexthop", skip_serializing_if = "Option::is_none")]
    pub nexthop: Option<String>,
}

impl VpcResourceFragmentRoutes {
    pub fn new() -> VpcResourceFragmentRoutes {
        VpcResourceFragmentRoutes {
            destination: None,
            nexthop: None,
        }
    }
}


