/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudServerRequestFragmentNics {
    #[serde(rename = "subnet_id")]
    pub subnet_id: String,
}

impl CloudServerRequestFragmentNics {
    pub fn new(subnet_id: String) -> CloudServerRequestFragmentNics {
        CloudServerRequestFragmentNics {
            subnet_id: subnet_id,
        }
    }
}
