/*
 * Open Service Cloud API
 *
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CloudProviderInfo {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Name>,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
}

impl CloudProviderInfo {
    pub fn new() -> CloudProviderInfo {
        CloudProviderInfo {
            name: None,
            parameters: None,
        }
    }
}

///
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Name {
    #[serde(rename = "huaweicloud")]
    Huaweicloud,
}
