/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenServiceCloudApi);
  }
}(this, function(expect, OpenServiceCloudApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenServiceCloudApi.BackupResourceFragment();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BackupResourceFragment', function() {
    it('should create an instance of BackupResourceFragment', function() {
      // uncomment below and update the code to test BackupResourceFragment
      //var instane = new OpenServiceCloudApi.BackupResourceFragment();
      //expect(instance).to.be.a(OpenServiceCloudApi.BackupResourceFragment);
    });

    it('should have the property volumeId (base name: "volume_id")', function() {
      // uncomment below and update the code to test the property volumeId
      //var instane = new OpenServiceCloudApi.BackupResourceFragment();
      //expect(instance).to.be();
    });

    it('should have the property container (base name: "container")', function() {
      // uncomment below and update the code to test the property container
      //var instane = new OpenServiceCloudApi.BackupResourceFragment();
      //expect(instance).to.be();
    });

    it('should have the property serviceMetadata (base name: "service_metadata")', function() {
      // uncomment below and update the code to test the property serviceMetadata
      //var instane = new OpenServiceCloudApi.BackupResourceFragment();
      //expect(instance).to.be();
    });

    it('should have the property snapshotId (base name: "snapshot_id")', function() {
      // uncomment below and update the code to test the property snapshotId
      //var instane = new OpenServiceCloudApi.BackupResourceFragment();
      //expect(instance).to.be();
    });

    it('should have the property isIncremental (base name: "is_incremental")', function() {
      // uncomment below and update the code to test the property isIncremental
      //var instane = new OpenServiceCloudApi.BackupResourceFragment();
      //expect(instance).to.be();
    });

  });

}));
