/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenServiceCloudApi);
  }
}(this, function(expect, OpenServiceCloudApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenServiceCloudApi.BlockVolumeRequestFragment();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BlockVolumeRequestFragment', function() {
    it('should create an instance of BlockVolumeRequestFragment', function() {
      // uncomment below and update the code to test BlockVolumeRequestFragment
      //var instane = new OpenServiceCloudApi.BlockVolumeRequestFragment();
      //expect(instance).to.be.a(OpenServiceCloudApi.BlockVolumeRequestFragment);
    });

    it('should have the property imageRef (base name: "imageRef")', function() {
      // uncomment below and update the code to test the property imageRef
      //var instane = new OpenServiceCloudApi.BlockVolumeRequestFragment();
      //expect(instance).to.be();
    });

    it('should have the property volumeType (base name: "volume_type")', function() {
      // uncomment below and update the code to test the property volumeType
      //var instane = new OpenServiceCloudApi.BlockVolumeRequestFragment();
      //expect(instance).to.be();
    });

    it('should have the property count (base name: "count")', function() {
      // uncomment below and update the code to test the property count
      //var instane = new OpenServiceCloudApi.BlockVolumeRequestFragment();
      //expect(instance).to.be();
    });

    it('should have the property sharable (base name: "sharable")', function() {
      // uncomment below and update the code to test the property sharable
      //var instane = new OpenServiceCloudApi.BlockVolumeRequestFragment();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instane = new OpenServiceCloudApi.BlockVolumeRequestFragment();
      //expect(instance).to.be();
    });

    it('should have the property multiattach (base name: "multiattach")', function() {
      // uncomment below and update the code to test the property multiattach
      //var instane = new OpenServiceCloudApi.BlockVolumeRequestFragment();
      //expect(instance).to.be();
    });

  });

}));
