/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenServiceCloudApi);
  }
}(this, function(expect, OpenServiceCloudApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenServiceCloudApi.CloudServerRequestFragment();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CloudServerRequestFragment', function() {
    it('should create an instance of CloudServerRequestFragment', function() {
      // uncomment below and update the code to test CloudServerRequestFragment
      //var instane = new OpenServiceCloudApi.CloudServerRequestFragment();
      //expect(instance).to.be.a(OpenServiceCloudApi.CloudServerRequestFragment);
    });

    it('should have the property imageRef (base name: "imageRef")', function() {
      // uncomment below and update the code to test the property imageRef
      //var instane = new OpenServiceCloudApi.CloudServerRequestFragment();
      //expect(instance).to.be();
    });

    it('should have the property flavorRef (base name: "flavorRef")', function() {
      // uncomment below and update the code to test the property flavorRef
      //var instane = new OpenServiceCloudApi.CloudServerRequestFragment();
      //expect(instance).to.be();
    });

    it('should have the property userData (base name: "user_data")', function() {
      // uncomment below and update the code to test the property userData
      //var instane = new OpenServiceCloudApi.CloudServerRequestFragment();
      //expect(instance).to.be();
    });

    it('should have the property adminPass (base name: "adminPass")', function() {
      // uncomment below and update the code to test the property adminPass
      //var instane = new OpenServiceCloudApi.CloudServerRequestFragment();
      //expect(instance).to.be();
    });

    it('should have the property keyName (base name: "key_name")', function() {
      // uncomment below and update the code to test the property keyName
      //var instane = new OpenServiceCloudApi.CloudServerRequestFragment();
      //expect(instance).to.be();
    });

    it('should have the property vpcid (base name: "vpcid")', function() {
      // uncomment below and update the code to test the property vpcid
      //var instane = new OpenServiceCloudApi.CloudServerRequestFragment();
      //expect(instance).to.be();
    });

    it('should have the property nics (base name: "nics")', function() {
      // uncomment below and update the code to test the property nics
      //var instane = new OpenServiceCloudApi.CloudServerRequestFragment();
      //expect(instance).to.be();
    });

    it('should have the property ipAddress (base name: "ip_address")', function() {
      // uncomment below and update the code to test the property ipAddress
      //var instane = new OpenServiceCloudApi.CloudServerRequestFragment();
      //expect(instance).to.be();
    });

    it('should have the property publicip (base name: "publicip")', function() {
      // uncomment below and update the code to test the property publicip
      //var instane = new OpenServiceCloudApi.CloudServerRequestFragment();
      //expect(instance).to.be();
    });

    it('should have the property count (base name: "count")', function() {
      // uncomment below and update the code to test the property count
      //var instane = new OpenServiceCloudApi.CloudServerRequestFragment();
      //expect(instance).to.be();
    });

    it('should have the property isAutoRename (base name: "isAutoRename")', function() {
      // uncomment below and update the code to test the property isAutoRename
      //var instane = new OpenServiceCloudApi.CloudServerRequestFragment();
      //expect(instance).to.be();
    });

    it('should have the property rootVolume (base name: "root_volume")', function() {
      // uncomment below and update the code to test the property rootVolume
      //var instane = new OpenServiceCloudApi.CloudServerRequestFragment();
      //expect(instance).to.be();
    });

    it('should have the property securityGroups (base name: "security_groups")', function() {
      // uncomment below and update the code to test the property securityGroups
      //var instane = new OpenServiceCloudApi.CloudServerRequestFragment();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instane = new OpenServiceCloudApi.CloudServerRequestFragment();
      //expect(instance).to.be();
    });

  });

}));
