/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenServiceCloudApi);
  }
}(this, function(expect, OpenServiceCloudApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenServiceCloudApi.CloudServerResourceFragment();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CloudServerResourceFragment', function() {
    it('should create an instance of CloudServerResourceFragment', function() {
      // uncomment below and update the code to test CloudServerResourceFragment
      //var instane = new OpenServiceCloudApi.CloudServerResourceFragment();
      //expect(instance).to.be.a(OpenServiceCloudApi.CloudServerResourceFragment);
    });

    it('should have the property hostId (base name: "hostId")', function() {
      // uncomment below and update the code to test the property hostId
      //var instane = new OpenServiceCloudApi.CloudServerResourceFragment();
      //expect(instance).to.be();
    });

    it('should have the property keyName (base name: "key_name")', function() {
      // uncomment below and update the code to test the property keyName
      //var instane = new OpenServiceCloudApi.CloudServerResourceFragment();
      //expect(instance).to.be();
    });

    it('should have the property oSEXTSTSvmState (base name: "OS-EXT-STS:vm_state")', function() {
      // uncomment below and update the code to test the property oSEXTSTSvmState
      //var instane = new OpenServiceCloudApi.CloudServerResourceFragment();
      //expect(instance).to.be();
    });

    it('should have the property addresses (base name: "addresses")', function() {
      // uncomment below and update the code to test the property addresses
      //var instane = new OpenServiceCloudApi.CloudServerResourceFragment();
      //expect(instance).to.be();
    });

    it('should have the property flavor (base name: "flavor")', function() {
      // uncomment below and update the code to test the property flavor
      //var instane = new OpenServiceCloudApi.CloudServerResourceFragment();
      //expect(instance).to.be();
    });

    it('should have the property oSEXTAZavailabilityZone (base name: "OS-EXT-AZ:availability_zone")', function() {
      // uncomment below and update the code to test the property oSEXTAZavailabilityZone
      //var instane = new OpenServiceCloudApi.CloudServerResourceFragment();
      //expect(instance).to.be();
    });

    it('should have the property accessIPv4 (base name: "accessIPv4")', function() {
      // uncomment below and update the code to test the property accessIPv4
      //var instane = new OpenServiceCloudApi.CloudServerResourceFragment();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instane = new OpenServiceCloudApi.CloudServerResourceFragment();
      //expect(instance).to.be();
    });

    it('should have the property osExtendedVolumesvolumesAttached (base name: "os-extended-volumes:volumes_attached")', function() {
      // uncomment below and update the code to test the property osExtendedVolumesvolumesAttached
      //var instane = new OpenServiceCloudApi.CloudServerResourceFragment();
      //expect(instance).to.be();
    });

    it('should have the property oSEXTSRVATTRhostname (base name: "OS-EXT-SRV-ATTR:hostname")', function() {
      // uncomment below and update the code to test the property oSEXTSRVATTRhostname
      //var instane = new OpenServiceCloudApi.CloudServerResourceFragment();
      //expect(instance).to.be();
    });

  });

}));
