/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenServiceCloudApi);
  }
}(this, function(expect, OpenServiceCloudApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenServiceCloudApi.ComputeResourceCreateRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ComputeResourceCreateRequest', function() {
    it('should create an instance of ComputeResourceCreateRequest', function() {
      // uncomment below and update the code to test ComputeResourceCreateRequest
      //var instane = new OpenServiceCloudApi.ComputeResourceCreateRequest();
      //expect(instance).to.be.a(OpenServiceCloudApi.ComputeResourceCreateRequest);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new OpenServiceCloudApi.ComputeResourceCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new OpenServiceCloudApi.ComputeResourceCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property availabilityZone (base name: "availability_zone")', function() {
      // uncomment below and update the code to test the property availabilityZone
      //var instane = new OpenServiceCloudApi.ComputeResourceCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property cloudProvider (base name: "cloud_provider")', function() {
      // uncomment below and update the code to test the property cloudProvider
      //var instane = new OpenServiceCloudApi.ComputeResourceCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property cloudServerRequestFragment (base name: "cloud_server_request_fragment")', function() {
      // uncomment below and update the code to test the property cloudServerRequestFragment
      //var instane = new OpenServiceCloudApi.ComputeResourceCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property physicalServerRequestFragment (base name: "physical_server_request_fragment")', function() {
      // uncomment below and update the code to test the property physicalServerRequestFragment
      //var instane = new OpenServiceCloudApi.ComputeResourceCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property podRequestFragment (base name: "pod_request_fragment")', function() {
      // uncomment below and update the code to test the property podRequestFragment
      //var instane = new OpenServiceCloudApi.ComputeResourceCreateRequest();
      //expect(instance).to.be();
    });

  });

}));
