/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenServiceCloudApi);
  }
}(this, function(expect, OpenServiceCloudApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenServiceCloudApi.ComputeResourceSpec();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ComputeResourceSpec', function() {
    it('should create an instance of ComputeResourceSpec', function() {
      // uncomment below and update the code to test ComputeResourceSpec
      //var instane = new OpenServiceCloudApi.ComputeResourceSpec();
      //expect(instance).to.be.a(OpenServiceCloudApi.ComputeResourceSpec);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new OpenServiceCloudApi.ComputeResourceSpec();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new OpenServiceCloudApi.ComputeResourceSpec();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new OpenServiceCloudApi.ComputeResourceSpec();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new OpenServiceCloudApi.ComputeResourceSpec();
      //expect(instance).to.be();
    });

    it('should have the property created (base name: "created")', function() {
      // uncomment below and update the code to test the property created
      //var instane = new OpenServiceCloudApi.ComputeResourceSpec();
      //expect(instance).to.be();
    });

    it('should have the property updated (base name: "updated")', function() {
      // uncomment below and update the code to test the property updated
      //var instane = new OpenServiceCloudApi.ComputeResourceSpec();
      //expect(instance).to.be();
    });

    it('should have the property cloudProvider (base name: "cloud_provider")', function() {
      // uncomment below and update the code to test the property cloudProvider
      //var instane = new OpenServiceCloudApi.ComputeResourceSpec();
      //expect(instance).to.be();
    });

    it('should have the property cloudServerFragment (base name: "cloud_server_fragment")', function() {
      // uncomment below and update the code to test the property cloudServerFragment
      //var instane = new OpenServiceCloudApi.ComputeResourceSpec();
      //expect(instance).to.be();
    });

    it('should have the property physicalServerFragment (base name: "physical_server_fragment")', function() {
      // uncomment below and update the code to test the property physicalServerFragment
      //var instane = new OpenServiceCloudApi.ComputeResourceSpec();
      //expect(instance).to.be();
    });

    it('should have the property podFragment (base name: "pod_fragment")', function() {
      // uncomment below and update the code to test the property podFragment
      //var instane = new OpenServiceCloudApi.ComputeResourceSpec();
      //expect(instance).to.be();
    });

  });

}));
