/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenServiceCloudApi);
  }
}(this, function(expect, OpenServiceCloudApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenServiceCloudApi.FileShareRequestFragment();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FileShareRequestFragment', function() {
    it('should create an instance of FileShareRequestFragment', function() {
      // uncomment below and update the code to test FileShareRequestFragment
      //var instane = new OpenServiceCloudApi.FileShareRequestFragment();
      //expect(instance).to.be.a(OpenServiceCloudApi.FileShareRequestFragment);
    });

    it('should have the property shareProto (base name: "share_proto")', function() {
      // uncomment below and update the code to test the property shareProto
      //var instane = new OpenServiceCloudApi.FileShareRequestFragment();
      //expect(instance).to.be();
    });

    it('should have the property shareType (base name: "share_type")', function() {
      // uncomment below and update the code to test the property shareType
      //var instane = new OpenServiceCloudApi.FileShareRequestFragment();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instane = new OpenServiceCloudApi.FileShareRequestFragment();
      //expect(instance).to.be();
    });

    it('should have the property shareNetworkId (base name: "share_network_id")', function() {
      // uncomment below and update the code to test the property shareNetworkId
      //var instane = new OpenServiceCloudApi.FileShareRequestFragment();
      //expect(instance).to.be();
    });

  });

}));
