/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenServiceCloudApi);
  }
}(this, function(expect, OpenServiceCloudApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenServiceCloudApi.PublicipResourceFragment();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PublicipResourceFragment', function() {
    it('should create an instance of PublicipResourceFragment', function() {
      // uncomment below and update the code to test PublicipResourceFragment
      //var instane = new OpenServiceCloudApi.PublicipResourceFragment();
      //expect(instance).to.be.a(OpenServiceCloudApi.PublicipResourceFragment);
    });

    it('should have the property profile (base name: "profile")', function() {
      // uncomment below and update the code to test the property profile
      //var instane = new OpenServiceCloudApi.PublicipResourceFragment();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new OpenServiceCloudApi.PublicipResourceFragment();
      //expect(instance).to.be();
    });

    it('should have the property publicIpAddress (base name: "public_ip_address")', function() {
      // uncomment below and update the code to test the property publicIpAddress
      //var instane = new OpenServiceCloudApi.PublicipResourceFragment();
      //expect(instance).to.be();
    });

    it('should have the property privateIpAddress (base name: "private_ip_address")', function() {
      // uncomment below and update the code to test the property privateIpAddress
      //var instane = new OpenServiceCloudApi.PublicipResourceFragment();
      //expect(instance).to.be();
    });

    it('should have the property portId (base name: "port_id")', function() {
      // uncomment below and update the code to test the property portId
      //var instane = new OpenServiceCloudApi.PublicipResourceFragment();
      //expect(instance).to.be();
    });

    it('should have the property createTime (base name: "create_time")', function() {
      // uncomment below and update the code to test the property createTime
      //var instane = new OpenServiceCloudApi.PublicipResourceFragment();
      //expect(instance).to.be();
    });

    it('should have the property bandwidthId (base name: "bandwidth_id")', function() {
      // uncomment below and update the code to test the property bandwidthId
      //var instane = new OpenServiceCloudApi.PublicipResourceFragment();
      //expect(instance).to.be();
    });

    it('should have the property bandwidthShareType (base name: "bandwidth_share_type")', function() {
      // uncomment below and update the code to test the property bandwidthShareType
      //var instane = new OpenServiceCloudApi.PublicipResourceFragment();
      //expect(instance).to.be();
    });

    it('should have the property bandwidthSize (base name: "bandwidth_size")', function() {
      // uncomment below and update the code to test the property bandwidthSize
      //var instane = new OpenServiceCloudApi.PublicipResourceFragment();
      //expect(instance).to.be();
    });

    it('should have the property bandwidthName (base name: "bandwidth_name")', function() {
      // uncomment below and update the code to test the property bandwidthName
      //var instane = new OpenServiceCloudApi.PublicipResourceFragment();
      //expect(instance).to.be();
    });

  });

}));
