/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenServiceCloudApi);
  }
}(this, function(expect, OpenServiceCloudApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenServiceCloudApi.StorageResourceCreateRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StorageResourceCreateRequest', function() {
    it('should create an instance of StorageResourceCreateRequest', function() {
      // uncomment below and update the code to test StorageResourceCreateRequest
      //var instane = new OpenServiceCloudApi.StorageResourceCreateRequest();
      //expect(instance).to.be.a(OpenServiceCloudApi.StorageResourceCreateRequest);
    });

    it('should have the property cloudProvider (base name: "cloud_provider")', function() {
      // uncomment below and update the code to test the property cloudProvider
      //var instane = new OpenServiceCloudApi.StorageResourceCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property availabilityZone (base name: "availability_zone")', function() {
      // uncomment below and update the code to test the property availabilityZone
      //var instane = new OpenServiceCloudApi.StorageResourceCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new OpenServiceCloudApi.StorageResourceCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new OpenServiceCloudApi.StorageResourceCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property size (base name: "size")', function() {
      // uncomment below and update the code to test the property size
      //var instane = new OpenServiceCloudApi.StorageResourceCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property blockVolumeRequestFragment (base name: "block_volume_request_fragment")', function() {
      // uncomment below and update the code to test the property blockVolumeRequestFragment
      //var instane = new OpenServiceCloudApi.StorageResourceCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property fileShareRequestFragment (base name: "file_share_request_fragment")', function() {
      // uncomment below and update the code to test the property fileShareRequestFragment
      //var instane = new OpenServiceCloudApi.StorageResourceCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property backupRequestFragment (base name: "backup_request_fragment")', function() {
      // uncomment below and update the code to test the property backupRequestFragment
      //var instane = new OpenServiceCloudApi.StorageResourceCreateRequest();
      //expect(instance).to.be();
    });

  });

}));
