/**
 * Open Service Cloud API
 * Open Service Cloud API to manage different backend cloud services.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: wanghui71leon@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenServiceCloudApi);
  }
}(this, function(expect, OpenServiceCloudApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenServiceCloudApi.StorageResourceSpec();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StorageResourceSpec', function() {
    it('should create an instance of StorageResourceSpec', function() {
      // uncomment below and update the code to test StorageResourceSpec
      //var instane = new OpenServiceCloudApi.StorageResourceSpec();
      //expect(instance).to.be.a(OpenServiceCloudApi.StorageResourceSpec);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new OpenServiceCloudApi.StorageResourceSpec();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new OpenServiceCloudApi.StorageResourceSpec();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new OpenServiceCloudApi.StorageResourceSpec();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new OpenServiceCloudApi.StorageResourceSpec();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instane = new OpenServiceCloudApi.StorageResourceSpec();
      //expect(instance).to.be();
    });

    it('should have the property cloudProvider (base name: "cloud_provider")', function() {
      // uncomment below and update the code to test the property cloudProvider
      //var instane = new OpenServiceCloudApi.StorageResourceSpec();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new OpenServiceCloudApi.StorageResourceSpec();
      //expect(instance).to.be();
    });

    it('should have the property availabilityZone (base name: "availability_zone")', function() {
      // uncomment below and update the code to test the property availabilityZone
      //var instane = new OpenServiceCloudApi.StorageResourceSpec();
      //expect(instance).to.be();
    });

    it('should have the property size (base name: "size")', function() {
      // uncomment below and update the code to test the property size
      //var instane = new OpenServiceCloudApi.StorageResourceSpec();
      //expect(instance).to.be();
    });

    it('should have the property blockVolumeFragment (base name: "block_volume_fragment")', function() {
      // uncomment below and update the code to test the property blockVolumeFragment
      //var instane = new OpenServiceCloudApi.StorageResourceSpec();
      //expect(instance).to.be();
    });

    it('should have the property fileShareFragment (base name: "file_share_fragment")', function() {
      // uncomment below and update the code to test the property fileShareFragment
      //var instane = new OpenServiceCloudApi.StorageResourceSpec();
      //expect(instance).to.be();
    });

    it('should have the property backupFragment (base name: "backup_fragment")', function() {
      // uncomment below and update the code to test the property backupFragment
      //var instane = new OpenServiceCloudApi.StorageResourceSpec();
      //expect(instance).to.be();
    });

  });

}));
